"""Albanian (Shqip) translations — auto-generated for Balkan Car Rentals v3.0.
UI mirrors config/i18n.py's English block key-for-key; TERMS mirrors config/terms.py."""

UI = {
    "nav_dashboard":     "Kreu",
    "nav_reservations":  "Rezervime",
    "nav_fleet":         "Flota",
    "nav_customers":     "Klientët",
    "nav_finance":       "Financa",
    "nav_settings":      "Cilësimet",
    "language":          "Gjuha",
    "coming_soon":       "Së shpejti.",
    "now_label":         "TANI",
    # auth
    "login_title":       "Hyrje e Sigurt",
    "login_username":    "Emri i përdoruesit",
    "login_password":    "Fjalëkalimi",
    "login_remember":    "Më mbaj mend (30 ditë)",
    "login_btn":         "Hyr",
    "login_failed":      "Emër përdoruesi/fjalëkalim i gabuar ose llogari joaktive.",
    "logout":            "Dil",
    "signed_in_as":      "Hyrë:",
    "default_admin_warning": "Hyrja e parazgjedhur admin/admin — ndryshojeni menjëherë te Cilësimet.",
    "access_denied":     "Nuk keni leje për ta parë këtë faqe.",
    # roles
    "role_super_admin":  "Super Administrator",
    "role_admin":        "Administrator",
    "role_employer":     "Agjent",
    "role_visitor":      "Vizitor",
    "role":              "Roli",
    # admin panel — role/permission matrix
    "nav_admin":         "Paneli i Administratorit",
    "admin_panel_title": "Paneli i Administratorit",
    "admin_users_title": "Llogaritë e Stafit",
    "admin_roles_title": "Rolet dhe Lejet",
    "admin_roles_hint_full": "Shënoni çfarë mund të bëjë secili rol. Super Administratori i ruan gjithmonë të gjitha lejet.",
    "admin_roles_hint_min": "Menaxhoni çfarë mund të bëjë një Agjent me regjistrimin e klientëve.",
    "perm_locked_hint":  "E fiksuar për siguri — nuk mund të ndryshohet.",
    "perm_overridden":   "Ndryshuar nga parazgjedhja",
    "save_changes":      "Ruaj Ndryshimet",
    "reset_defaults":    "Kthe te Parazgjedhjet",
    "unsaved_changes":   "ndryshim(e) të paruajtura",
    "permgroup_general": "Të përgjithshme",
    "permgroup_client_registration": "Regjistrimi i Klientit",
    "permgroup_fleet":   "Flota",
    "permgroup_finance": "Financa",
    "permgroup_administration": "Administrimi",
    "perm_view_dashboard":        "Shiko kreun",
    "perm_view_reservations":     "Shiko rezervimet",
    "perm_view_fleet":            "Shiko flotën",
    "perm_view_management":       "Hyr në faqet e menaxhimit",
    "perm_create_reservation":    "Krijo rezervim",
    "perm_cancel_reservation":    "Anulo rezervim",
    "perm_service_vehicle":       "Servis i automjetit",
    "perm_edit_fleet":            "Modifiko flotën",
    "perm_soft_delete_vehicle":   "Arkivo automjetin",
    "perm_view_finance":          "Shiko financat",
    "perm_manage_users":          "Menaxho përdoruesit",
    "perm_backup_database":       "Rezervo bazën e të dhënave",
    "perm_assign_admin_roles":    "Cakto role administratori",
    "perm_hard_delete_vehicle":   "Fshi përgjithmonë automjetin",
    "perm_edit_business_settings": "Modifiko cilësimet e biznesit",
    "permission":        "Leja",
    # shared UI atoms (date picker, dialogs, booking form)
    "today":             "Sot",
    "close":             "Mbyll",
    "cancel":            "Anulo",
    "pick_a_date":       "Zgjidhni një datë",
    "time":              "Ora",
    "month":             "Muaji",
    "year":              "Viti",
    "preset_today":      "Sot",
    "preset_last_week":  "Javën e kaluar",
    "preset_next_week":  "Javën e ardhshme",
    "preset_next_month": "Muajin e ardhshëm",
    "preset_last_month": "Muajin e kaluar",
    "rental_period":     "Periudha e Qirasë",
    "client_info":       "Të dhënat e Klientit",
    "deal_terms":        "Automjeti dhe Çmimi",
    "cars_free":         "Automjete të lira",
    "invoice_preview":   "Pamja paraprake e faturës",
    "invoice_preview_hint": "Pamje e drejtpërdrejtë — PDF-ja përfundimtare gjenerohet në ruajtje.",
    "terms_title":       "Kushtet e Qirasë",
    # dashboard
    "dashboard_title":   "Përmbledhje",
    "dashboard_help":    "Gjendja e flotës në kohë reale dhe afati kohor i qirave.",
    "timeline_title":    "Afati Kohor i Zënies së Flotës",
    "timeline_help":     "Çdo rresht është një automjet. Kaloni mbi një bllok për të parë klientin. Vija vertikale = tani.",
    "timeline_empty":    "Asnjë qira aktive për momentin.",
    "kpi_total":         "Automjete Gjithsej",
    "kpi_available":     "Të Lira",
    "kpi_rented":        "Me Qira",
    "kpi_garage":        "Në Garazh / Mirëmbajtje",
    # availability
    "availability_title":"Disponueshmëria & Llogaritësi i Kthimit",
    "availability_help": "Zgjidhni një datë dhe orë; aplikacioni llogarit momentin e kthimit.",
    "start_date":        "Data e Fillimit",
    "start_time":        "Ora e Marrjes",
    "days":              "Numri i Ditëve",
    "return_time":       "Ora e Kthimit",
    "return_date":       "Data e Kthimit",
    "calculated_return": "Kthimi i Llogaritur",
    "available_cars":    "Automjete të Lira në Këtë Periudhë",
    "no_cars":           "Asnjë automjet i lirë për këtë periudhë.",
    "select_car":        "Zgjidhni një automjet",
    "quick_register":    "Regjistrim i Shpejtë i Qirasë",
    "quick_register_help":"Plotësoni të dhënat e klientit. Totali përditësohet drejtpërdrejt teksa ndryshoni tarifën.",
    "client_name":       "Emri i Plotë i Klientit",
    "client_phone":      "Telefon / WhatsApp",
    "client_id":         "Nr. i Letërnjoftimit / Pasaportës",
    "negotiated_rate":   "Tarifa Ditore e Negociuar",
    "negotiated_rate_help":"E parazgjedhur sipas çmimit të listës. Ndryshojeni — totali përditësohet drejtpërdrejt.",
    "deposit":           "Depozita e Marrë",
    "live_total":        "Totali Aktual",
    "register_btn":      "Ruaj Qiranë",
    "register_ok":       "Qiraja u ruajt",
    "register_need_fields":"Emri dhe telefoni i klientit janë të detyrueshëm.",
    "allow_past_dates":  "Lejo data të kaluara",
    # fleet table
    "fleet_title":       "Gjithë Flota",
    "fleet_help":        "Çdo automjet. Kërkoni sipas markës, targës ose kodit.",
    "search":            "Kërko…",
    "col_id":            "Kodi i Automjetit",
    "col_model":         "Marka / Modeli",
    "col_year":          "Viti",
    "col_plate":         "Targa",
    "col_color":         "Ngjyra",
    "col_mileage":       "Kilometrazhi",
    "col_status":        "Statusi",
    "col_rate":          "Tarifa Ditore",
    "col_notes":         "Shënime",
    "col_count":         "automjete",
    # status labels
    "Available":         "E Lirë",
    "Rented":            "Me Qira",
    "In Garage":         "Në Garazh",
    "Maintenance":       "Mirëmbajtje",
    "DELETED":           "Arkivuar",
    # fleet CRUD
    "fleet_add":         "Shto Automjet",
    "fleet_edit":        "Modifiko Automjetin",
    "fleet_delete":      "Fshi / Arkivo",
    "fleet_add_help":    "Kodi i automjetit caktohet automatikisht.",
    "fleet_edit_help":   "Zgjidhni automjetin për ta përditësuar.",
    "fleet_delete_help": "Administratori mund të arkivojë; Super Administratori mund të fshijë përgjithmonë.",
    "add_btn":           "Shto",
    "update_btn":        "Përditëso",
    "theme_save_btn":    "Ruaj",
    "theme_reset_btn":   "Rikthe te parazgjedhjet",
    "added_ok":          "Automjeti u shtua.",
    "updated_ok":        "Automjeti u përditësua.",
    "soft_delete":       "Arkivo",
    "hard_delete":       "Fshi përgjithmonë",
    "delete_confirm":    "E konfirmoj këtë veprim",
    "soft_deleted_done": "Automjeti u arkivua.",
    "hard_deleted_done": "Automjeti u fshi përgjithmonë.",
    "archived_list":     "Automjete të Arkivuara",
    "select_vehicle":    "Zgjidhni një automjet",
    "restore_btn":       "Rikthe",
    "restored_ok":       "Automjeti u rikthye në flotën aktive.",
    # reservations
    "reservations_title":"Rezervime",
    "reservations_help": "Krijoni, shikoni dhe anuloni qira.",
    "active_reservations":"Qira Aktive",
    "no_active_reservations":"Asnjë qira aktive.",
    "search_active":     "Kërko qiratë aktive…",
    "no_search_results": "Asnjë qira nuk përputhet me kërkimin.",
    "cancel_btn":        "Anulo",
    "cancel_done":       "Qiraja u anulua.",
    "col_customer":      "Klienti",
    "col_car":           "Automjeti",
    "col_period":        "Periudha",
    "col_deal":          "Kontrata",
    "col_days":          "Ditë",
    "col_total":         "Totali",
    "col_deposit":       "Depozita",
    "col_overdue":       "Me Vonesë",
    "no_create_perm":    "Ju nevojitet të paktën roli Agjent për të krijuar qira.",
    "overdue_badge":     "ME VONESË",
    "overdue_detail":    "{h:.0f} orë vonesë",
    # customers
    "customers_title":   "Regjistri i Klientëve",
    "card_open":         "Hap",
    "open_full_table":   "Hap Tabelën e Plotë",
    "customers_help":    "Të gjithë klientët e regjistruar dhe historiku i tyre i qirave.",
    "customer_search":   "Kërko klientë…",
    "col_rentals":       "Qira",
    "col_last_rental":   "Qiraja e Fundit",
    "col_phone":         "Telefoni",
    "col_idno":          "Letërnjoftim / Pasaportë",
    "no_customers":      "Ende asnjë klient.",
    "customer_history":  "Historiku i Qirave",
    # finance
    "finance_title":     "Financa",
    "finance_help":      "Zërat e të ardhurave dhe ndarja sipas automjetit.",
    "total_revenue":     "Të Ardhura Gjithsej",
    "rental_revenue":    "Të Ardhura nga Qiraja",
    "penalty_revenue":   "Gjoba për Vonesa",
    "damage_revenue":    "Arkëtim Dëmesh",
    "by_vehicle":        "Të Ardhura sipas Automjetit",
    "no_finance_data":   "Ende asnjë aktivitet financiar.",
    "monthly_chart":     "Të Ardhura Mujore",
    "col_income":        "Të Ardhura",
    # settings
    "settings_title":    "Cilësimet",
    "settings_help":     "Të dhënat e biznesit, menaxhimi i përdoruesve dhe fjalëkalimi.",
    "tab_business":      "Biznesi",
    "tab_users":         "Përdoruesit",
    "tab_roles":         "Rolet",
    "tab_password":      "Fjalëkalimi",
    "business_settings": "Të Dhënat e Biznesit",
    "business_name":     "Emri i Biznesit",
    "business_name_help":"Shfaqet në shiritin e sipërm dhe në ekranin e hyrjes.",
    "business_saved":    "Të dhënat e biznesit u përditësuan.",
    "save_btn":          "Ruaj",
    "user_management":   "Menaxhimi i Përdoruesve",
    "create_user":       "Përdorues i Ri",
    "full_name":         "Emri i Plotë",
    "add_user_btn":      "Shto Përdorues",
    "user_created":      "Përdoruesi u krijua.",
    "user_deleted":      "Përdoruesi u fshi.",
    "cannot_delete_self": "Nuk mund të fshini llogarinë tuaj.",
    "users_list":        "Përdoruesit Ekzistues",
    "active":            "Aktiv",
    "deactivate":        "Çaktivizo",
    "inactive":          "Joaktiv",
    "activate":          "Aktivizo",
    "change_role":       "Ndrysho Rolin",
    "role_updated":      "Roli u përditësua.",
    "change_password":   "Ndrysho Fjalëkalimin",
    "current_password":  "Fjalëkalimi Aktual",
    "new_password":      "Fjalëkalimi i Ri",
    "confirm_password":  "Fjalëkalimi i Ri (përsëri)",
    "pw_changed":        "Fjalëkalimi u përditësua.",
    "pw_mismatch":       "Fjalëkalimet e reja nuk përputhen.",
    "fields_required":   "Ju lutemi plotësoni të gjitha fushat e detyrueshme.",
    "role_not_allowed":  "Nuk lejoheni ta caktoni atë rol.",
    "password_too_short":  "Fjalëkalimi duhet të ketë të paktën {n} karaktere.",
    "user_exists":       "Ai emër përdoruesi ekziston tashmë.",
    "wrong_current":     "Fjalëkalimi aktual është i gabuar.",
    "manage_rental":     "Menaxho / Kthim",
    "return_btn":        "Përpuno Kthimin & Mbyll",
    "late_fee":          "Gjobë për Vonesë",
    "damage_charge":     "Tarifë Dëmi",
    "return_notes":      "Shënime Kthimi / Gjendjeje",
    "contract_signed":   "Kontrata u Nënshkrua",
    "return_done":       "Automjeti u kthye dhe qiraja u mbyll.",
    # finance — costs & evaluation
    "fin_tab_overview":  "Përmbledhje",
    "fin_tab_monthly":   "Mujore",
    "fin_tab_yearly":    "Vjetore",
    "fin_tab_vehicle":   "Sipas Automjetit",
    "fin_tab_customer":  "Sipas Klientit",
    "fin_tab_costs":     "Shpenzime",
    "fin_tab_compensation": "Kompensim",
    "fin_greeting":      "Përshëndetje",
    "fin_report_statistic": "Statistikat e Raportit",
    "fin_current_period":   "Aktuale",
    "by_customer_revenue":"Të ardhura sipas klientit",
    "download_csv":      "Shkarko CSV",
    "download_pdf":      "Shkarko PDF",
    "download_timeline": "Shkarko Afatin Kohor (PDF)",
    "report_metric":     "Zëri",
    "total_cost":        "Shpenzime Gjithsej",
    "net_profit":        "Fitimi Neto",
    "profit_margin":     "Marzhi i Fitimit",
    "income_vs_cost":    "Të Ardhura & Shpenzime",
    "monthly_eval":      "Të Ardhura / Shpenzime / Neto Mujore",
    "yearly_eval":       "Të Ardhura / Shpenzime / Neto Vjetore",
    "col_cost":          "Shpenzim",
    "col_net":           "Neto",
    "col_year":          "Viti",
    "by_vehicle_profit": "Përfitueshmëria sipas Automjetit",
    "cost_breakdown":    "Shpenzime sipas Llojit",
    "add_cost_section":  "Shto Shpenzim Automjeti",
    "edit_cost_section": "Redakto Shpenzimin e Automjetit",
    "editing_badge":     "Duke Redaktuar",
    "invalid_vehicle":   "Automjeti i zgjedhur nuk ekziston më.",
    "invalid_type":      "Zgjidhni një lloj të vlefshëm.",
    "invalid_date":      "Vendosni një datë të vlefshme.",
    "invalid_amount":    "Vendosni një shumë të vlefshme.",
    "amount_too_large":  "Shuma është shumë e madhe.",
    "note_too_long":     "Shënimi është shumë i gjatë (maksimumi 300 shkronja).",
    "invalid_deal_id":   "ID e qirasë e pavlefshme.",
    "cost_type":         "Lloji i Shpenzimit",
    "cost_amount":       "Shuma",
    "cost_date":         "Data",
    "cost_note":         "Shënim",
    "add_cost_btn":      "Shto Shpenzim",
    "cost_added":        "Shpenzimi u regjistrua.",
    "recent_costs":      "Shpenzimet e Fundit",
    "no_costs":          "Ende asnjë shpenzim i regjistruar.",
    "delete_btn":        "Fshi",
    "cost_insurance":    "Sigurim",
    "cost_maintenance":  "Mirëmbajtje / Riparim",
    "cost_depreciation": "Amortizim",
    "cost_fuel":         "Karburant",
    "cost_financing":    "Financim / Kredi",
    "cost_registration": "Regjistrim / Taksa",
    "cost_other":        "Tjetër",
    "add_compensation_section": "Shto Kompensim Dëmi",
    "edit_compensation_section": "Redakto Kompensimin e Dëmit",
    "comp_type":         "Lloji i Kompensimit",
    "add_compensation_btn": "Shto Kompensim",
    "comp_damage":       "Dëmtim",
    "comp_mechanic_fee": "Tarifë Mekaniku",
    "comp_traffic_fine": "Gjobë Trafiku",
    "comp_cleaning_fee": "Tarifë Pastrimi",
    "comp_fuel_shortage": "Mungesë Karburanti",
    "comp_lost_item":    "Send i Humbur",
    "comp_other":        "Tjetër",
    # invoice
    "invoice_heading":   "FATURË",
    "bill_to":           "Faturuar Për",
    "invoice_no":        "Nr. i Faturës",
    "invoice_date":      "Data",
    "invoice_vehicle":   "Automjeti",
    "invoice_period":    "Periudha e Qirasë",
    "invoice_desc":      "Përshkrimi",
    "invoice_qty":       "Ditë",
    "invoice_unit":      "Çmimi për Njësi",
    "invoice_amount":    "Shuma",
    "invoice_line_rental":"Qira Automjeti",
    "invoice_line_deposit":"Depozitë",
    "invoice_subtotal":  "Nëntotali",
    "invoice_total":     "TOTALI I PËRGJITHSHËM",
    "invoice_balance":   "Bilanci për t'u Paguar",
    "invoice_thanks":    "Faleminderit për besimin tuaj.",
    "invoice_print":     "🖨️ Printo Faturën",
    "invoice_download":  "⬇️ Shkarko Faturën (PDF)",
    "invoice_ready":     "Fatura është gati — printojeni ose shkarkojeni më poshtë.",
    "invoice_signed":    "Kontrata u nënshkrua",
    "invoice_unsigned":  "Kontrata nuk u nënshkrua",
    "invoice_footer":    "Ky dokument u krijua nga kompjuteri.",
    "show_invoice":      "🧾 Krijo / Shiko Faturën",
    # activity log
    "tab_activity":      "Aktiviteti",
    "activity_log":      "Regjistri i Aktivitetit",
    "no_activity":       "Ende asnjë aktivitet i regjistruar.",
    "col_when":          "Kur",
    "col_user":          "Përdoruesi",
    "col_action":        "Veprimi",
    "col_entity":        "Entiteti",
    "col_detail":        "Detaji",
    "close_btn":         "Mbyll",
    # reservation creator / customer registrar
    "invoice_issued_by": "Emri i punonjësit",
    "col_registered_by": "Regjistruar nga",
    # return reminders (due-soon alert / overdue alarm)
    "due_soon_badge":    "AFRON AFATI",
    "due_soon_detail":   "{h:.0f} orë mbeten",
    "notif_overdue_title":  "Kthime me vonesë",
    "notif_due_soon_title": "Kthime brenda {n} orëve",
    "notif_overdue_by":  "{h:.0f} orë vonesë",
    "notif_due_in":      "për {h:.0f} orë",
    # language preference (Settings)
    "tab_language":      "Gjuha",
    "language_help":     "Gjuha e ndërfaqes ruhet dhe mbahet mend në hyrjen tuaj të radhës.",
    "lang_saved":        "Preferenca e gjuhës u ruajt.",
    # admin account management
    "manage_account":    "Menaxho Llogarinë",
    "change_username":   "Ndrysho Emrin e Përdoruesit",
    "username_changed":  "Emri i përdoruesit u përditësua.",
    "reset_password":    "Rivendos Fjalëkalimin",
    "pw_reset_done":     "Fjalëkalimi u rivendos.",
    # vehicle photos
    "vehicle_photo":         "Foto e Automjetit (opsionale)",
    "vehicle_photo_help":    "Opsionale — JPG/PNG/WEBP. Mund të shtohet më vonë.",
    "vehicle_photo_replace": "Zëvendëso Foton (opsionale)",
    "vehicle_photo_remove":  "Hiq foton aktuale",
    "vehicle_photos":        "Foto të Automjetit (opsionale)",
    "manage_photos":         "Menaxho Fotot",
    "no_photos":             "Ende asnjë foto.",
    "add_photos":            "Shto Foto",
    "photos_added":          "Fotot u shtuan.",
    "available_now":         "Të Lira Tani",
    "no_available_now":      "Asnjë automjet i lirë për momentin.",
    "per_day":               "ditë",
    # customer edit / invoice / reassign
    "edit_customer":         "Modifiko të Dhënat e Klientit",
    "customer_saved":        "Të dhënat e klientit u përditësuan.",
    "print_invoice":         "Printo Faturën",
    "choose_client_language": "Zgjidhni gjuhën e klientit",
    "reassign_registered_by": "Ricakto Regjistruesin",
    "apply_btn":             "Zbato",
    "registered_by_updated": "Regjistruesi u përditësua.",
    # rental popup + invoice language/terms
    "open_rental_btn":       "Regjistro Qira",
    "rent_card_btn":         "Merr me Qira",
    "invoice_language":      "Gjuha e Faturës",
    "not_available_window":  "Ky automjet nuk është i lirë për datat e zgjedhura.",
    "invoice_terms_heading": "Kushtet & Rregullat",
    # notification bell + whatsapp
    "notifications_title":   "Kujtues",
    "no_reminders":          "Asnjë kujtues për momentin.",
    "whatsapp_msg":          "WhatsApp",
    "whatsapp_call":         "Telefono",
    "phone_copy_hint":       "Prekni ikonën e kopjimit për të kopjuar numrin:",
    "wa_reminder":           "Përshëndetje {name}, qiraja juaj për {car} skadon më {due}. Ju lutemi ktheheni në kohë. Faleminderit.",
    # license / annual unlock
    "tab_license":           "Licenca",
    "license_help":          "Menaxhimi i licencës vjetore. Kalendarët kufizohen deri në vitin e licencuar.",
    "license_status":        "I licencuar deri më {y}.",
    "unlock_next_year":      "Shkyç {y}",
    "year_unlocked":         "Viti u shkyç.",
    "generate_license_invoice": "Gjenero Faturë Licence",
    "license_invoice_title": "Faturë Licence Softueri",
    "license_licensee":      "Mbajtësi i Licencës",
    "license_product":       "Produkti",
    "license_period":        "Periudha e Licencës",
    "license_years":         "Vite",
    "license_amount":        "Shuma",
    "license_purchase_date": "Data e Blerjes",
    "notif_license_title":   "Rinovimi i Licencës",
    "notif_license_msg":     "Licenca juaj skadon më {date} ({days} ditë të mbetura). Ju lutemi rinovoni.",
    # license cap — refused dates beyond the licensed year
    "license_year_locked":   "Kjo datë është jashtë periudhës së licencës. Jeni të licencuar deri më {y}.",
    "license_cap_note":      "I licencuar deri më 31.12.{y}. Për {y2} nevojitet një çelës i ri licence.",
    "license_locked_title":  "Kufiri i licencës",
    # SMTP
    "smtp_settings":         "Cilësimet e Email-it (SMTP)",
    "smtp_help":             "Për email-et e rikuperimit të fjalëkalimit. Mund të lihet bosh për momentin.",
    "smtp_configured":       "I konfiguruar",
    "smtp_not_set":          "I pakonfiguruar (fjalëkalimi i ri shfaqet në ekran)",
    "smtp_from":             "Adresa e dërguesit",
    # profile email
    "my_profile":            "Profili Im",
    "email_label":           "Email",
    "email_help":            "Përdoret për rikuperimin e fjalëkalimit.",
    "email_saved":           "Email-i u ruajt.",
    "reset_password_help":   "Gjeneron një fjalëkalim të ri dhe e dërgon me email (e shfaq në ekran nëse nuk ka SMTP).",
    # password recovery
    "forgot_password":       "Harrova fjalëkalimin",
    "recover_sent_generic":    "Nëse përputhet një llogari, një lidhje rivendosjeje u dërgua në adresën e saj të email-it.",
    "reset_password_title":    "Vendos një fjalëkalim të ri",
    "reset_btn":               "Përditëso fjalëkalimin",
    "password_reset_done":               "Fjalëkalimi u përditësua. Tani mund të hyni.",
    "back_to_login":           "Kthehu te hyrja",
    "reset_token_invalid":     "Kjo lidhje është e pavlefshme ose është përdorur tashmë.",
    "reset_token_expired":     "Kjo lidhje ka skaduar. Ju lutemi kërkoni një të re.",
    "account_locked":          "Shumë përpjekje të dështuara. Llogaria është bllokuar përkohësisht — provoni më vonë.",
    "password_too_simple":     "Fjalëkalimi duhet të përmbajë të paktën tre nga: shkronja të vogla, të mëdha, shifra, simbole.",
    "password_too_common":     "Ky fjalëkalim është shumë i zakonshëm. Zgjidhni një më të fortë.",
    "password_contains_username": "Fjalëkalimi nuk mund të përmbajë emrin tuaj të përdoruesit.",
    "password_too_long":       "Fjalëkalimi është shumë i gjatë (maksimumi 72 bajt).",
    "password_reused":         "Fjalëkalimi i ri duhet të ndryshojë nga ai aktual.",
    "passwords_no_match":      "Fjalëkalimet nuk përputhen.",
    "password_too_simple_hint": "Shto të gjitha karakteret e nevojshme për një fjalëkalim të sigurt.",
    "password_min_chars":      "Minimumi {n} karaktere",
    "password_need_upper":     "Një shkronjë e madhe",
    "password_need_lower":     "Një shkronjë e vogël",
    "password_need_special":   "Një karakter special",
    "password_need_digit":     "Një shifër",
    "password_rules":          "Të paktën {n} karaktere, me të paktën tre nga: shkronja të vogla, të mëdha, shifra, simbole.",
    "recover_help":          "Shkruani emrin e përdoruesit ose adresën e email-it. Nëse përputhet një llogari, do të dërgohet një lidhje rivendosjeje.",
    "recover_btn":           "Dërgo lidhjen e rivendosjes",
    "recover_sent":          "Një fjalëkalim i ri u dërgua me email te {to}.",
    "recover_fallback":      "SMTP nuk është konfiguruar. Fjalëkalimi i ri: {pw} (do të dërgohej me email te {to}).",
    "recover_admin_only":    "Kjo veçori është e disponueshme vetëm për Administrator / Super Administrator.",
    # activity masking + filter
    "filter_action":         "Filtro sipas veprimit",
    "filter_by":             "Filtro sipas",
    "status_locked_rented":  "Statusi është i kyçur ndërsa ky automjet është në qira aktive.",
    "system_admin_label":    "administrator sistemi",
    # company logo / profile / licenses / vehicle status
    "company_logo":          "Logoja e kompanisë",
    "logo_help":             "Shfaqet në çdo faturë. PNG/JPG; ripërmasohet për t'u përshtatur.",
    "upload_logo":           "Ngarko logon",
    "remove_logo":           "Hiq logon",
    "logo_saved":            "Logoja u ruajt.",
    "logo_removed":          "Logoja u hoq.",
    # company stamp (invoice signature seal) + invoice signature lines
    "company_stamp":         "Vula e kompanisë",
    "stamp_help":            "Shfaqet në zonën e nënshkrimit të çdo fature (si vula e kompanisë). PNG/JPG; ripërmasohet për t'u përshtatur.",
    "upload_stamp":          "Ngarko vulën",
    "remove_stamp":          "Hiq vulën",
    "stamp_saved":           "Vula u ruajt.",
    "stamp_removed":         "Vula u hoq.",
    "invoice_customer_signature":   "Nënshkrimi i klientit",
    "invoice_authorized_signature": "Nënshkrimi i autorizuar",
    # business contact + invoice quick-links QR buttons
    "business_contact":      "Kontakti i biznesit & QR i faturës",
    "contact_help":          "Përdoret për butonat QR të lidhjeve të shpejta të faturës (WhatsApp, kartë kontakti, drejtime).",
    "business_phone":        "Telefoni i biznesit",
    "business_address":      "Adresa e biznesit",
    "business_maps_url":     "Lidhja e hartës / drejtimeve (opsionale)",
    "business_email":        "Email-i i biznesit (opsional)",
    "contact_saved":         "Të dhënat e kontaktit u ruajtën.",
    "pay_qr_enable":         "Aktivizo QR-në e pagesës (transfertë) në fatura",
    "pay_qr_help":           "Shton një QR transferte SEPA për bilancin e mbetur. Kërkon IBAN-in më poshtë.",
    "business_iban":         "IBAN",
    "currency_settings":     "Monedha",
    "currency_label":        "Monedha e shfaqjes",
    "currency_rate_label":   "Kursi (1 EUR = ? ALL)",
    "currency_help":         "Shumat ruhen gjithmonë në EUR; kjo kontrollon vetëm cila monedhë shfaqet.",
    "invoice_quick_links":   "Lidhje të shpejta — Skano",
    "qr_pay":                "Paguaj bilancin",
    "qr_whatsapp":           "Na shkruaj në WhatsApp",
    "qr_contact":            "Ruaj kontaktin",
    "qr_location":           "Na gjej / kthe makinën",
    "qr_summary":            "Përmbledhja e qirasë",
    "qa_total":              "Totali i qirasë",
    "qa_iban":               "Banka / IBAN",
    "qa_return":             "Adresa e kthimit",
    "qa_balance":            "Shuma e mbetur",
    "qa_call":               "Na telefononi",
    "qr_scan_hint":          "Skano me telefon",
    # theme customization (super-admin) + night mode
    "select_theme":          "Zgjidh temën",
    "theme_font":            "Fonti",
    "theme_primary":         "Ngjyra parësore",
    "theme_secondary":       "Ngjyra dytësore",
    "theme_success":         "Ngjyra e suksesit",
    "theme_warning":         "Ngjyra e paralajmërimit",
    "theme_alert":           "Ngjyra e alarmit",
    "theme_disabled":        "Ngjyra joaktive",
    "theme_bg":              "Ngjyra e sfondit",
    "theme_saved":           "Tema u ruajt.",
    "theme_reset":           "Rikthe parazgjedhjen",
    "theme_help":            "Zgjidh fontin dhe ngjyrat e markës. Vlen për të gjithë përdoruesit.",
    "night_mode":            "Modaliteti i natës",
    "day_mode":              "Modaliteti i ditës",
    "tab_profile":           "Profili",
    "profile_saved":         "Profili u përditësua.",
    "license_records":       "Regjistrat e licencave",
    "add_license":           "Shto licencë",
    "edit_license":          "Redakto licencën",
    "delete_license":        "Fshi licencën",
    "license_added":         "Licenca u shtua.",
    "license_updated":       "Licenca u përditësua.",
    "license_deleted":       "Licenca u fshi.",
    "no_licenses":           "Ende nuk ka regjistra licencash.",
    "col_actions":           "Veprimet",
    "to_garage":             "Në garazh",
    "to_maintenance":        "Në mirëmbajtje",
    "to_available":          "Bëje të disponueshëm",
    "status_updated":        "Statusi u përditësua.",
    "edit_btn":              "Redakto",
    "last_super_admin":      "Nuk mund të hiqet super-administratori i fundit.",
    # finance totals + year lock + return activity (v3.0 round 4)
    "fin_totals":            "Totalet",
    "set_licensed_year_label":"Cakto vitin e licencuar",
    "licensed_year_saved":   "Viti i licencuar u përditësua.",
    "return_activity":       "Kthe veprimin",
    "activity_returned":     "Veprimi u kthye.",
    "return_activity_help":  "Rikthe automjetet e arkivuara dhe qiratë e anuluara.",
    # customers split (round 5)
    "active_renters":        "Qiramarrësit aktivë",
    "no_active_renters":     "Asnjë klient nuk po qiraron aktualisht.",
    "all_customers":         "Të gjithë klientët",
    "open_customer":         "Hap klientin",
    # reset data + visitor hero — round 6
    "danger_zone":           "Zona e rrezikut",
    "reset_finance_btn":     "Rivendos të dhënat financiare",
    "reset_fleet_btn":       "Rivendos të dhënat e flotës",
    "reset_finance_help":    "Fshin të gjitha të ardhurat (tarifat) dhe shpenzimet. Automjetet dhe qiratë ruhen.",
    "reset_fleet_help":      "Fshin të gjitha automjetet, fotot, qiratë dhe të dhënat financiare të tyre. Klientët ruhen. Flota e parazgjedhur ringarkohet në rinisjen tjetër.",
    "reset_confirm_label":   "Shkruaj RESET për të konfirmuar",
    "reset_done":            "Të dhënat u rivendosën.",
    "visitor_hero":          "Shfletoni makinat tona të disponueshme",
    "visitor_hero_sub":      "Zgjidhni makinën e duhur nga flota jonë. Kontaktoni ekipin tonë për të rezervuar.",
    "contact_to_book":       "Na kontaktoni për të rezervuar",
    # sidebar toggle (round 7)
    "open_sidebar":          "Hap menynë",
    "collapse_sidebar":      "Mbyll menynë",
    # data management — delete finance / client records (round 8)
    "tab_data":              "Të dhëna",
    "data_help":             "Fshini regjistrime financiare ose klientësh individualë, ose pastrojini të gjitha. Vetëm Super Administratori.",
    "finance_records_section":"Regjistrime Financiare",
    "client_records_section": "Regjistrime Klientësh",
    "income_records":        "Të ardhura (Tarifa)",
    "expense_records":       "Shpenzime (Kosto)",
    "no_finance_records":    "Nuk ka regjistrime financiare.",
    "col_type":              "Lloji",
    "charge_rental":         "Qira",
    "charge_overdue_penalty":"Gjobë vonese",
    "charge_damage":         "Dëmtim",
    "charge_deposit":        "Kapar",
    "charge_refund":         "Rimbursim",
    "record_deleted":        "Regjistrimi u fshi.",
    "client_deleted":        "Klienti dhe qiratë e tij u fshinë.",
    "delete_client_help":    "Fshin përgjithmonë këtë klient bashkë me qiratë dhe tarifat e tij.",
    "reset_clients_btn":     "Rivendos të dhënat e klientëve",
    "reset_clients_help":    "Fshin çdo klient me qiratë e tij dhe tarifat përkatëse. Automjetet ruhen dhe lirohen si të disponueshme.",
    # edit reservation + finance reports / month drill-down (v3.1)
    "edit_reservation":      "Modifiko rezervimin",
    "cancel_reservation":    "Anulo rezervimin",
    "change_car":            "Ndrysho automjetin",
    "keep_current_car":      "Mbaj automjetin aktual",
    "rental_updated":        "Rezervimi u përditësua.",
    "select_month":          "Zgjidh një muaj",
    "all_months":            "Të gjithë muajt",
    "month_detail":          "Detaje mujore",
    "report_total":          "TOTALI",
    "report_generated":      "Krijuar",
    "report_period":         "Periudha",
    "report_business":       "Biznesi",
    # duplicated invoice copies (customer + office)
    "invoice_copy_customer": "Kopja e klientit",
    "invoice_copy_office":   "Kopja e zyrës",
    # add-reservation modal + timeline export range (v3.2)
    "add_reservation":       "Shto rezervim",
    "tl_export_range":       "Intervali i eksportit",
    "tl_range_week":         "Këtë javë",
    "tl_range_month":        "Këtë muaj",
    "tl_range_year":         "Këtë vit",
    "tl_range_two":          "Intervali dymujor",
    "tl_range_all":          "Të gjithë muajt (faqe të veçanta)",
    "tl_pick_start_month":   "Muaji fillestar",
    # timeline view buttons + show-done toggle (v3.3)
    "view_day":              "Ditë",
    "view_week":             "Javë",
    "view_month":            "Muaj",
    "view_year":             "Vit",
    "view_today":            "Sot",
    "show_done":             "Shfaq të përfunduarat",
}

TERMS = {
    "title": "KUSHTET E QIRASË SË AUTOMJETIT & PËRGJEGJËSIA PËR DËME",
    "rules": [
        "Automjeti duhet të përdoret në përputhje me rregullat e qarkullimit. Respektimi i kufijve të shpejtësisë është i detyrueshëm.",
        "Sipas politikës së kompanisë, shpejtësia maksimale e funksionimit të automjeteve është 120 km/h. Nëse tejkalohet kufiri prej 120 km/h, klienti është përgjegjës për çdo dëmtim të motorit, turbos, transmisionit ose dëmtim mekanik të shkaktuar nga shpejtësia e tepërt. Të dhënat GPS dhe regjistrimet e shpejtësisë së automjetit pranohen si provë e vlefshme.",
        "Pirja e duhanit brenda automjetit është rreptësisht e ndaluar. Kostot e pastrimit, riparimit ose zëvendësimit për erën e cigares, gjurmët e djegies ose dëmtimet e sediljeve/tapicerisë i ngarkohen klientit.",
        "Dëmtimi i sediljeve, tapicerisë, pjesëve plastike, ekranit multimedial ose pajisjeve të brendshme mbulohet nga klienti.",
        "Dëmtimet që vijnë nga shpërthimi i gomave, deformimi i disqeve, përplasja me trotuar, keqpërdorimi ose pakujdesia janë përgjegjësi e klientit.",
        "Plasaritjet dhe çarjet në xhamin e përparmë, fenerët, pasqyrat ose dritaret mbulohen nga klienti në rast gabimi ose neglizhence të përdoruesit.",
        "Të gjitha kostot që vijnë nga përdorimi i karburantit të gabuar i ngarkohen klientit.",
        "Nëse çelësi i automjetit humbet, thyhet ose dëmtohet, kostoja e një çelësi të ri, softuerit dhe tërheqjes me karrotrec i ngarkohet klientit.",
        "Gjobat e qarkullimit, tarifat e autostradës, gjobat e parkimit dhe tarifat e kalimit paguhen nga qiramarrësi.",
        "Gjatë dorëzimit merren regjistrime video dhe foto. Gjendja e automjetit në momentin e dorëzimit pranohet si regjistrimi zyrtar.",
        "Kompania përdor një sistem gjurmimi automjeti (GPS) për qëllime sigurie dhe menaxhimi të flotës.",
        "Automjeti duhet të kthehet me të njëjtin nivel karburanti me të cilin u mor.",
        "Kthimi me vonesë: automjeti duhet të kthehet në datën dhe orën e rënë dakord. Çdo ditë e nisur vonesë faturohet si një ditë e plotë qiraje shtesë; gjithashtu mund të zbatohet një gjobë për kthim me vonesë.",
    ],
}
