"""Spanish (Español) translations — auto-generated for Balkan Car Rentals v3.0.
UI mirrors config/i18n.py's English block key-for-key; TERMS mirrors config/terms.py."""

UI = {
    "nav_dashboard":     "Inicio",
    "nav_reservations":  "Reservas",
    "nav_fleet":         "Flota",
    "nav_customers":     "Clientes",
    "nav_finance":       "Finanzas",
    "nav_settings":      "Ajustes",
    "language":          "Idioma",
    "coming_soon":       "Próximamente.",
    "now_label":         "AHORA",
    # auth
    "login_title":       "Inicio de sesión seguro",
    "login_username":    "Usuario",
    "login_password":    "Contraseña",
    "login_remember":    "Recordarme (30 días)",
    "login_btn":         "Iniciar sesión",
    "login_failed":      "Usuario/contraseña incorrectos o cuenta inactiva.",
    "logout":            "Cerrar sesión",
    "signed_in_as":      "Sesión iniciada:",
    "default_admin_warning": "Acceso predeterminado admin/admin — cámbielo ahora en Ajustes.",
    "access_denied":     "No tiene permiso para ver esta página.",
    # roles
    "role_super_admin":  "Súper administrador",
    "role_admin":        "Administrador",
    "role_employer":     "Agente",
    "role_visitor":      "Visitante",
    "role":              "Rol",
    # dashboard
    "dashboard_title":   "Resumen",
    "dashboard_help":    "Estado de la flota en vivo y cronograma de alquileres.",
    "timeline_title":    "Cronograma de ocupación de la flota",
    "timeline_help":     "Cada fila es un vehículo. Pase el cursor sobre un bloque para ver el cliente. Línea vertical = ahora.",
    "timeline_empty":    "No hay alquileres activos en este momento.",
    "kpi_total":         "Vehículos totales",
    "kpi_available":     "Disponibles",
    "kpi_rented":        "Alquilados",
    "kpi_garage":        "En garaje / Mantenimiento",
    # availability
    "availability_title":"Disponibilidad y cálculo de devolución",
    "availability_help": "Elija una fecha y hora; la aplicación calcula el momento de devolución.",
    "start_date":        "Fecha de inicio",
    "start_time":        "Hora de recogida",
    "days":              "Número de días",
    "return_time":       "Hora de devolución",
    "return_date":       "Fecha de devolución",
    "calculated_return": "Devolución calculada",
    "available_cars":    "Vehículos disponibles en este periodo",
    "no_cars":           "No hay vehículos libres para este periodo.",
    "select_car":        "Seleccione un vehículo",
    "quick_register":    "Registro rápido de alquiler",
    "quick_register_help":"Introduzca los datos del cliente. El total se actualiza en vivo al cambiar la tarifa.",
    "client_name":       "Nombre completo del cliente",
    "client_phone":      "Teléfono / WhatsApp",
    "client_id":         "N.º de DNI / Pasaporte",
    "negotiated_rate":   "Tarifa diaria acordada",
    "negotiated_rate_help":"Por defecto es el precio de lista. Cámbiela — el total se actualiza en vivo.",
    "deposit":           "Depósito recibido",
    "live_total":        "Total actual",
    "register_btn":      "Guardar alquiler",
    "register_ok":       "Alquiler guardado",
    "register_need_fields":"El nombre y el teléfono del cliente son obligatorios.",
    # fleet table
    "fleet_title":       "Flota completa",
    "fleet_help":        "Todos los vehículos. Busque por marca, matrícula o código.",
    "search":            "Buscar…",
    "col_id":            "Código de vehículo",
    "col_model":         "Marca / Modelo",
    "col_year":          "Año",
    "col_plate":         "Matrícula",
    "col_color":         "Color",
    "col_mileage":       "Kilometraje",
    "col_status":        "Estado",
    "col_rate":          "Tarifa diaria",
    "col_notes":         "Notas",
    "col_count":         "vehículos",
    # status labels
    "Available":         "Disponible",
    "Rented":            "Alquilado",
    "In Garage":         "En garaje",
    "Maintenance":       "Mantenimiento",
    "DELETED":           "Archivado",
    # fleet CRUD
    "fleet_add":         "Añadir vehículo",
    "fleet_edit":        "Editar vehículo",
    "fleet_delete":      "Eliminar / Archivar",
    "fleet_add_help":    "El código de vehículo se asigna automáticamente.",
    "fleet_edit_help":   "Seleccione el vehículo a actualizar.",
    "fleet_delete_help": "El administrador puede archivar; el súper administrador puede eliminar permanentemente.",
    "add_btn":           "Añadir",
    "update_btn":        "Actualizar",
    "added_ok":          "Vehículo añadido.",
    "updated_ok":        "Vehículo actualizado.",
    "soft_delete":       "Archivar",
    "hard_delete":       "Eliminar permanentemente",
    "delete_confirm":    "Confirmo esta acción",
    "soft_deleted_done": "Vehículo archivado.",
    "hard_deleted_done": "Vehículo eliminado permanentemente.",
    "archived_list":     "Vehículos archivados",
    "select_vehicle":    "Seleccione un vehículo",
    "restore_btn":       "Restaurar",
    "restored_ok":       "Vehículo restaurado a la flota activa.",
    # reservations
    "reservations_title":"Reservas",
    "reservations_help": "Cree, consulte y cancele alquileres.",
    "active_reservations":"Alquileres activos",
    "no_active_reservations":"No hay alquileres activos.",
    "search_active":     "Buscar alquileres activos…",
    "no_search_results": "Ningún alquiler coincide con la búsqueda.",
    "cancel_btn":        "Cancelar",
    "cancel_done":       "Alquiler cancelado.",
    "col_customer":      "Cliente",
    "col_car":           "Vehículo",
    "col_period":        "Periodo",
    "col_deal":          "Contrato",
    "col_days":          "Días",
    "col_total":         "Total",
    "col_deposit":       "Depósito",
    "col_overdue":       "Vencido",
    "no_create_perm":    "Necesita al menos el rol de Agente para crear alquileres.",
    "overdue_badge":     "VENCIDO",
    "overdue_detail":    "{h:.0f} h de retraso",
    # customers
    "customers_title":   "Directorio de clientes",
    "card_open":         "Abrir",
    "open_full_table":   "Abrir tabla completa",
    "customers_help":    "Todos los clientes registrados y su historial de alquileres.",
    "customer_search":   "Buscar clientes…",
    "col_rentals":       "Alquileres",
    "col_last_rental":   "Último alquiler",
    "col_phone":         "Teléfono",
    "col_idno":          "DNI / Pasaporte",
    "no_customers":      "Aún no hay clientes.",
    "customer_history":  "Historial de alquileres",
    # finance
    "finance_title":     "Finanzas",
    "finance_help":      "Líneas de ingresos y desglose por vehículo.",
    "total_revenue":     "Ingresos totales",
    "rental_revenue":    "Ingresos por alquiler",
    "penalty_revenue":   "Penalizaciones por retraso",
    "damage_revenue":    "Recuperación por daños",
    "by_vehicle":        "Ingresos por vehículo",
    "no_finance_data":   "Aún no hay actividad financiera.",
    "monthly_chart":     "Ingresos mensuales",
    "col_income":        "Ingresos",
    # settings
    "settings_title":    "Ajustes",
    "settings_help":     "Datos del negocio, gestión de usuarios y contraseña.",
    "tab_business":      "Negocio",
    "tab_users":         "Usuarios",
    "tab_password":      "Contraseña",
    "business_settings": "Datos del negocio",
    "business_name":     "Nombre del negocio",
    "business_name_help":"Se muestra en la barra superior y en la pantalla de inicio de sesión.",
    "business_saved":    "Datos del negocio actualizados.",
    "save_btn":          "Guardar",
    "user_management":   "Gestión de usuarios",
    "create_user":       "Nuevo usuario",
    "full_name":         "Nombre completo",
    "add_user_btn":      "Añadir usuario",
    "user_created":      "Usuario creado.",
    "user_deleted":      "Usuario eliminado.",
    "cannot_delete_self": "No puedes eliminar tu propia cuenta.",
    "users_list":        "Usuarios existentes",
    "active":            "Activo",
    "deactivate":        "Desactivar",
    "inactive":          "Inactivo",
    "activate":          "Activar",
    "change_role":       "Cambiar rol",
    "role_updated":      "Rol actualizado.",
    "change_password":   "Cambiar contraseña",
    "current_password":  "Contraseña actual",
    "new_password":      "Nueva contraseña",
    "confirm_password":  "Nueva contraseña (de nuevo)",
    "pw_changed":        "Contraseña actualizada.",
    "pw_mismatch":       "Las nuevas contraseñas no coinciden.",
    "fields_required":   "Por favor, rellene todos los campos obligatorios.",
    "role_not_allowed":  "No tiene permiso para asignar ese rol.",
    "password_too_short":"La contraseña debe tener al menos 6 caracteres.",
    "user_exists":       "Ese nombre de usuario ya existe.",
    "wrong_current":     "La contraseña actual es incorrecta.",
    "manage_rental":     "Gestionar / Devolución",
    "return_btn":        "Procesar devolución y cerrar",
    "late_fee":          "Penalización por retraso",
    "damage_charge":     "Cargo por daños",
    "return_notes":      "Notas de devolución / estado",
    "contract_signed":   "Contrato firmado",
    "return_done":       "Vehículo devuelto y alquiler cerrado.",
    # finance — costs & evaluation
    "fin_tab_overview":  "Resumen",
    "fin_tab_monthly":   "Mensual",
    "fin_tab_yearly":    "Anual",
    "fin_tab_vehicle":   "Por vehículo",
    "fin_tab_customer":  "Por cliente",
    "fin_tab_costs":     "Costes",
    "by_customer_revenue":"Ingresos por cliente",
    "download_csv":      "Descargar CSV",
    "download_pdf":      "Descargar PDF",
    "download_timeline": "Descargar Cronograma (PDF)",
    "report_metric":     "Concepto",
    "total_cost":        "Coste total",
    "net_profit":        "Beneficio neto",
    "profit_margin":     "Margen de beneficio",
    "income_vs_cost":    "Ingresos y costes",
    "monthly_eval":      "Ingresos / Costes / Neto mensual",
    "yearly_eval":       "Ingresos / Costes / Neto anual",
    "col_cost":          "Coste",
    "col_net":           "Neto",
    "col_year":          "Año",
    "by_vehicle_profit": "Rentabilidad por vehículo",
    "cost_breakdown":    "Coste por tipo",
    "add_cost_section":  "Añadir coste de vehículo",
    "cost_type":         "Tipo de coste",
    "cost_amount":       "Importe",
    "cost_date":         "Fecha",
    "cost_note":         "Nota",
    "add_cost_btn":      "Añadir coste",
    "cost_added":        "Coste registrado.",
    "recent_costs":      "Costes recientes",
    "no_costs":          "Aún no hay costes registrados.",
    "delete_btn":        "Eliminar",
    "cost_insurance":    "Seguro",
    "cost_maintenance":  "Mantenimiento / Reparación",
    "cost_depreciation": "Depreciación",
    "cost_fuel":         "Combustible",
    "cost_financing":    "Financiación / Préstamo",
    "cost_registration": "Matriculación / Impuestos",
    "cost_other":        "Otros",
    # invoice
    "invoice_heading":   "FACTURA",
    "bill_to":           "Facturar a",
    "invoice_no":        "N.º de factura",
    "invoice_date":      "Fecha",
    "invoice_vehicle":   "Vehículo",
    "invoice_period":    "Periodo de alquiler",
    "invoice_desc":      "Descripción",
    "invoice_qty":       "Días",
    "invoice_unit":      "Precio unitario",
    "invoice_amount":    "Importe",
    "invoice_line_rental":"Alquiler de vehículo",
    "invoice_line_deposit":"Depósito",
    "invoice_subtotal":  "Subtotal",
    "invoice_total":     "TOTAL GENERAL",
    "invoice_balance":   "Saldo pendiente",
    "invoice_thanks":    "Gracias por su confianza.",
    "invoice_print":     "🖨️ Imprimir factura",
    "invoice_download":  "⬇️ Descargar factura (PDF)",
    "invoice_ready":     "Factura lista — imprímala o descárguela a continuación.",
    "invoice_signed":    "Contrato firmado",
    "invoice_unsigned":  "Contrato no firmado",
    "invoice_footer":    "Este documento ha sido generado por ordenador.",
    "show_invoice":      "🧾 Crear / Ver factura",
    # activity log
    "tab_activity":      "Actividad",
    "activity_log":      "Registro de actividad",
    "no_activity":       "Aún no hay actividad registrada.",
    "col_when":          "Cuándo",
    "col_user":          "Usuario",
    "col_action":        "Acción",
    "col_entity":        "Entidad",
    "col_detail":        "Detalle",
    "close_btn":         "Cerrar",
    # reservation creator / customer registrar
    "invoice_issued_by": "Nombre del empleado",
    "col_registered_by": "Registrado por",
    # return reminders (due-soon alert / overdue alarm)
    "due_soon_badge":    "PRÓXIMO A VENCER",
    "due_soon_detail":   "{h:.0f} h restantes",
    "notif_overdue_title":  "Devoluciones vencidas",
    "notif_due_soon_title": "Devoluciones en menos de {n} h",
    "notif_overdue_by":  "{h:.0f} h de retraso",
    "notif_due_in":      "en {h:.0f} h",
    # language preference (Settings)
    "tab_language":      "Idioma",
    "language_help":     "Su idioma de interfaz se guarda y se recuerda en su próximo inicio de sesión.",
    "lang_saved":        "Preferencia de idioma guardada.",
    # admin account management
    "manage_account":    "Gestionar cuenta",
    "change_username":   "Cambiar nombre de usuario",
    "username_changed":  "Nombre de usuario actualizado.",
    "reset_password":    "Restablecer contraseña",
    "pw_reset_done":     "Contraseña restablecida.",
    # vehicle photos
    "vehicle_photo":         "Foto del vehículo (opcional)",
    "vehicle_photo_help":    "Opcional — JPG/PNG/WEBP. Se puede añadir más tarde.",
    "vehicle_photo_replace": "Reemplazar foto (opcional)",
    "vehicle_photo_remove":  "Quitar foto actual",
    "vehicle_photos":        "Fotos del vehículo (opcional)",
    "manage_photos":         "Gestionar fotos",
    "no_photos":             "Aún no hay fotos.",
    "add_photos":            "Añadir fotos",
    "photos_added":          "Fotos añadidas.",
    "available_now":         "Disponibles ahora",
    "no_available_now":      "No hay vehículos disponibles en este momento.",
    "per_day":               "día",
    # customer edit / invoice / reassign
    "edit_customer":         "Editar datos del cliente",
    "customer_saved":        "Datos del cliente actualizados.",
    "print_invoice":         "Imprimir factura",
    "choose_client_language": "Elija el idioma del cliente",
    "reassign_registered_by": "Reasignar registrado por",
    "apply_btn":             "Aplicar",
    "registered_by_updated": "Registrado por actualizado.",
    # rental popup + invoice language/terms
    "open_rental_btn":       "Registrar alquiler",
    "rent_card_btn":         "Alquilar",
    "invoice_language":      "Idioma de la factura",
    "not_available_window":  "Este vehículo no está disponible en las fechas seleccionadas.",
    "invoice_terms_heading": "Términos y condiciones",
    # notification bell + whatsapp
    "notifications_title":   "Recordatorios",
    "no_reminders":          "No hay recordatorios en este momento.",
    "whatsapp_msg":          "WhatsApp",
    "whatsapp_call":         "Llamar",
    "phone_copy_hint":       "Toque el icono de copiar para copiar el número:",
    "wa_reminder":           "Hola {name}, la devolución de su alquiler de {car} vence el {due}. Por favor, devuélvalo a tiempo. Gracias.",
    # license / annual unlock
    "tab_license":           "Licencia",
    "license_help":          "Gestión de licencia anual. Los calendarios se limitan al año licenciado.",
    "license_status":        "Licenciado hasta {y}.",
    "unlock_next_year":      "Desbloquear {y}",
    "year_unlocked":         "Año desbloqueado.",
    "generate_license_invoice": "Generar factura de licencia",
    "license_invoice_title": "Factura de licencia de software",
    "license_licensee":      "Licenciatario",
    "license_product":       "Producto",
    "license_period":        "Periodo de licencia",
    "license_years":         "Años",
    "license_amount":        "Importe",
    "license_purchase_date": "Fecha de compra",
    "notif_license_title":   "Renovación de Licencia",
    "notif_license_msg":     "Su licencia caduca el {date} (quedan {days} días). Por favor, renueve.",
    # SMTP
    "smtp_settings":         "Ajustes de correo (SMTP)",
    "smtp_help":             "Para correos de recuperación de contraseña. Puede dejarse vacío por ahora.",
    "smtp_configured":       "Configurado",
    "smtp_not_set":          "No configurado (la nueva contraseña se muestra en pantalla)",
    "smtp_from":             "Dirección de remitente",
    # profile email
    "my_profile":            "Mi perfil",
    "email_label":           "Correo electrónico",
    "email_help":            "Se usa para la recuperación de contraseña.",
    "email_saved":           "Correo electrónico guardado.",
    "reset_password_help":   "Genera una nueva contraseña y la envía por correo (la muestra en pantalla si no hay SMTP).",
    # password recovery
    "forgot_password":       "Olvidé mi contraseña",
    "recover_help":          "Para cuentas de Administrador / Súper administrador. Los demás usuarios deben consultar a su administrador.",
    "recover_btn":           "Restablecer y enviar nueva contraseña",
    "recover_sent":          "Se envió una nueva contraseña a {to}.",
    "recover_fallback":      "SMTP no configurado. Nueva contraseña: {pw} (se habría enviado a {to}).",
    "recover_admin_only":    "Esta función solo está disponible para Administrador / Súper administrador.",
    # activity masking + filter
    "filter_action":         "Filtrar por acción",
    "filter_by":             "Filtrar por",
    "status_locked_rented":  "El estado está bloqueado mientras este vehículo está en alquiler activo.",
    "system_admin_label":    "administrador del sistema",
    # company logo / profile / licenses / vehicle status
    "company_logo":          "Logotipo de la empresa",
    "logo_help":             "Aparece en cada factura. PNG/JPG; se redimensiona para ajustarse.",
    "upload_logo":           "Subir logotipo",
    "remove_logo":           "Eliminar logotipo",
    "logo_saved":            "Logotipo guardado.",
    "logo_removed":          "Logotipo eliminado.",
    # company stamp (invoice signature seal) + invoice signature lines
    "company_stamp":         "Sello de la empresa",
    "stamp_help":            "Aparece en el área de firma de cada factura (como sello de la empresa). PNG/JPG; se redimensiona para ajustarse.",
    "upload_stamp":          "Subir sello",
    "remove_stamp":          "Eliminar sello",
    "stamp_saved":           "Sello guardado.",
    "stamp_removed":         "Sello eliminado.",
    "invoice_customer_signature":   "Firma del cliente",
    "invoice_authorized_signature": "Firma autorizada",
    # business contact + invoice quick-links QR buttons
    "business_contact":      "Contacto de empresa y QR de factura",
    "contact_help":          "Se usa para los botones QR de enlaces rápidos de la factura (WhatsApp, tarjeta de contacto, indicaciones).",
    "business_phone":        "Teléfono de empresa",
    "business_address":      "Dirección de empresa",
    "business_maps_url":     "Enlace de mapa / indicaciones (opcional)",
    "business_email":        "Correo de empresa (opcional)",
    "contact_saved":         "Datos de contacto guardados.",
    "pay_qr_enable":         "Activar QR de pago (transferencia) en facturas",
    "pay_qr_help":           "Añade un QR de transferencia SEPA para el saldo pendiente. Requiere el IBAN de abajo.",
    "business_iban":         "IBAN",
    "invoice_quick_links":   "Enlaces rápidos — Escanear",
    "qr_pay":                "Pagar el saldo",
    "qr_whatsapp":           "Escríbenos por WhatsApp",
    "qr_contact":            "Guardar contacto",
    "qr_location":           "Encuéntranos / devolución",
    "qr_summary":            "Resumen del alquiler",
    "qr_scan_hint":          "Escanea con tu teléfono",
    # theme customization (super-admin) + night mode
    "select_theme":          "Elegir tema",
    "theme_font":            "Fuente",
    "theme_primary":         "Color primario",
    "theme_secondary":       "Color secundario",
    "theme_success":         "Color de éxito",
    "theme_warning":         "Color de aviso",
    "theme_alert":           "Color de alerta",
    "theme_disabled":        "Color deshabilitado",
    "theme_bg":              "Color de fondo",
    "theme_saved":           "Tema guardado.",
    "theme_reset":           "Restablecer",
    "theme_help":            "Elige la fuente y los colores de marca. Se aplica a todos los usuarios.",
    "night_mode":            "Modo noche",
    "day_mode":              "Modo día",
    "tab_profile":           "Perfil",
    "profile_saved":         "Perfil actualizado.",
    "license_records":       "Registros de licencia",
    "add_license":           "Añadir licencia",
    "edit_license":          "Editar licencia",
    "delete_license":        "Eliminar licencia",
    "license_added":         "Licencia añadida.",
    "license_updated":       "Licencia actualizada.",
    "license_deleted":       "Licencia eliminada.",
    "no_licenses":           "Aún no hay registros de licencia.",
    "col_actions":           "Acciones",
    "to_garage":             "Llevar al garaje",
    "to_maintenance":        "Poner en mantenimiento",
    "to_available":          "Marcar como disponible",
    "status_updated":        "Estado actualizado.",
    "edit_btn":              "Editar",
    "last_super_admin":      "No se puede eliminar el último superadministrador.",
    # finance totals + year lock + return activity (v3.0 round 4)
    "fin_totals":            "Totales",
    "set_licensed_year_label":"Establecer año con licencia",
    "licensed_year_saved":   "Año con licencia actualizado.",
    "return_activity":       "Revertir actividad",
    "activity_returned":     "Actividad revertida.",
    "return_activity_help":  "Restaurar vehículos archivados y alquileres cancelados.",
    # customers split (round 5)
    "active_renters":        "Clientes con alquiler activo",
    "no_active_renters":     "Ningún cliente tiene un alquiler activo.",
    "all_customers":         "Todos los clientes",
    "open_customer":         "Abrir cliente",
    # reset data + visitor hero — round 6
    "danger_zone":           "Zona de peligro",
    "reset_finance_btn":     "Restablecer datos financieros",
    "reset_fleet_btn":       "Restablecer datos de flota",
    "reset_finance_help":    "Elimina todos los registros de ingresos (cargos) y costos. Se conservan vehículos y alquileres.",
    "reset_fleet_help":      "Elimina todos los vehículos, fotos, alquileres y sus registros financieros. Se conservan los clientes. La flota predeterminada se recarga al reiniciar.",
    "reset_confirm_label":   "Escribe RESET para confirmar",
    "reset_done":            "Datos restablecidos.",
    "visitor_hero":          "Explora nuestros coches disponibles",
    "visitor_hero_sub":      "Elige el coche adecuado de nuestra flota. Contacta con nuestro equipo para reservar.",
    "contact_to_book":       "Contáctanos para reservar",
    # sidebar toggle (round 7)
    "open_sidebar":          "Abrir barra lateral",
    "collapse_sidebar":      "Contraer barra lateral",
    # data management — delete finance / client records (round 8)
    "tab_data":              "Datos",
    "data_help":             "Elimina registros financieros o de clientes individuales, o bórralos todos. Solo Super Administrador.",
    "finance_records_section":"Registros Financieros",
    "client_records_section": "Registros de Clientes",
    "income_records":        "Ingresos (Cargos)",
    "expense_records":       "Gastos (Costos)",
    "no_finance_records":    "No hay registros financieros.",
    "col_type":              "Tipo",
    "charge_rental":         "Alquiler",
    "charge_overdue_penalty":"Penalización por retraso",
    "charge_damage":         "Daños",
    "charge_deposit":        "Depósito",
    "charge_refund":         "Reembolso",
    "record_deleted":        "Registro eliminado.",
    "client_deleted":        "Cliente y sus alquileres eliminados.",
    "delete_client_help":    "Elimina permanentemente este cliente junto con sus alquileres y cargos.",
    "reset_clients_btn":     "Restablecer datos de clientes",
    "reset_clients_help":    "Elimina todos los clientes con sus alquileres y los cargos asociados. Los vehículos se conservan y quedan disponibles.",
    # edit reservation + finance reports / month drill-down (v3.1)
    "edit_reservation":      "Editar reserva",
    "change_car":            "Cambiar vehículo",
    "keep_current_car":      "Mantener el vehículo actual",
    "rental_updated":        "Reserva actualizada.",
    "select_month":          "Seleccionar un mes",
    "all_months":            "Todos los meses",
    "month_detail":          "Detalle del mes",
    "report_total":          "TOTAL",
    "report_generated":      "Generado",
    "report_period":         "Período",
    "report_business":       "Empresa",
    # duplicated invoice copies (customer + office)
    "invoice_copy_customer": "Copia del cliente",
    "invoice_copy_office":   "Copia de oficina",
    # add-reservation modal + timeline export range (v3.2)
    "add_reservation":       "Añadir reserva",
    "tl_export_range":       "Intervalo de exportación",
    "tl_range_week":         "Esta semana",
    "tl_range_month":        "Este mes",
    "tl_range_year":         "Este año",
    "tl_range_two":          "Intervalo de dos meses",
    "tl_range_all":          "Todos los meses (páginas separadas)",
    "tl_pick_start_month":   "Mes inicial",
    # timeline view buttons + show-done toggle (v3.3)
    "view_day":              "Día",
    "view_week":             "Semana",
    "view_month":            "Mes",
    "view_year":             "Año",
    "view_today":            "Hoy",
    "show_done":             "Mostrar completados",
}

TERMS = {
    "title": "CONDICIONES DE ALQUILER DE VEHÍCULOS Y RESPONSABILIDAD POR DAÑOS",
    "rules": [
        "El vehículo debe utilizarse de acuerdo con las normas de tráfico. El cumplimiento de los límites de velocidad es obligatorio.",
        "Por política de la empresa, la velocidad máxima de uso de los vehículos es de 120 km/h. Si se supera el límite de 120 km/h, el cliente será responsable de cualquier avería de motor, turbo, transmisión o mecánica causada por el exceso de velocidad. Los datos GPS y los registros de velocidad del vehículo se aceptan como prueba válida.",
        "Está estrictamente prohibido fumar dentro del vehículo. Los costes de limpieza, reparación o sustitución por olor a cigarrillo, marcas de quemaduras o daños en los asientos/tapicería se cargan al cliente.",
        "Los daños en los asientos, la tapicería, las piezas de plástico, la pantalla multimedia o el equipamiento interior corren a cargo del cliente.",
        "Los daños derivados de reventones de neumáticos, llantas dobladas, golpes contra un bordillo, uso indebido o descuido son responsabilidad del cliente.",
        "Las grietas y desconchones en el parabrisas, los faros, los espejos o las ventanillas corren a cargo del cliente en caso de error del usuario o negligencia.",
        "Todos los costes derivados del uso de combustible incorrecto se cargan al cliente.",
        "Si se pierde, rompe o daña la llave del vehículo, el coste de una nueva llave, el software y la grúa se cargan al cliente.",
        "Las multas de tráfico, los peajes de autopista, las multas de aparcamiento y los cargos de paso corren a cargo del arrendatario.",
        "En la entrega se realizan grabaciones de vídeo y fotografías. El estado del vehículo en el momento de la entrega se acepta como registro oficial.",
        "La empresa utiliza un sistema de seguimiento de vehículos (GPS) con fines de seguridad y gestión de la flota.",
        "El vehículo debe devolverse con el mismo nivel de combustible con el que se recibió.",
        "Devolución tardía: el vehículo debe devolverse en la fecha y hora acordadas. Cada día comenzado de retraso se cobra como un día de alquiler adicional completo; además puede aplicarse una penalización por demora.",
    ],
}
