"""German (Deutsch) translations — auto-generated for Balkan Car Rentals v3.0.
UI mirrors config/i18n.py's English block key-for-key; TERMS mirrors config/terms.py."""

UI = {
    "nav_dashboard":     "Startseite",
    "nav_reservations":  "Reservierungen",
    "nav_fleet":         "Flotte",
    "nav_customers":     "Kunden",
    "nav_finance":       "Finanzen",
    "nav_settings":      "Einstellungen",
    "language":          "Sprache",
    "coming_soon":       "Demnächst verfügbar.",
    "now_label":         "JETZT",
    # auth
    "login_title":       "Sichere Anmeldung",
    "login_username":    "Benutzername",
    "login_password":    "Passwort",
    "login_remember":    "Angemeldet bleiben (30 Tage)",
    "login_btn":         "Anmelden",
    "login_failed":      "Falscher Benutzername/Passwort oder Konto inaktiv.",
    "logout":            "Abmelden",
    "signed_in_as":      "Angemeldet:",
    "default_admin_warning": "Standard-Login admin/admin — ändern Sie es jetzt in den Einstellungen.",
    "access_denied":     "Sie haben keine Berechtigung, diese Seite anzuzeigen.",
    # roles
    "role_super_admin":  "Super-Administrator",
    "role_admin":        "Administrator",
    "role_employer":     "Agent",
    "role_visitor":      "Besucher",
    "role":              "Rolle",
    # dashboard
    "dashboard_title":   "Übersicht",
    "dashboard_help":    "Aktueller Flottenstatus und Mietzeitachse.",
    "timeline_title":    "Flottenauslastungs-Zeitachse",
    "timeline_help":     "Jede Zeile ist ein Fahrzeug. Bewegen Sie den Mauszeiger über einen Block, um den Kunden zu sehen. Vertikale Linie = jetzt.",
    "timeline_empty":    "Derzeit keine aktiven Mietverträge.",
    "kpi_total":         "Fahrzeuge gesamt",
    "kpi_available":     "Verfügbar",
    "kpi_rented":        "Vermietet",
    "kpi_garage":        "In Werkstatt / Wartung",
    # availability
    "availability_title":"Verfügbarkeits- und Rückgaberechner",
    "availability_help": "Wählen Sie Datum und Uhrzeit; die App berechnet den Rückgabezeitpunkt.",
    "start_date":        "Startdatum",
    "start_time":        "Abholzeit",
    "days":              "Anzahl der Tage",
    "return_time":       "Rückgabezeit",
    "return_date":       "Rückgabedatum",
    "calculated_return": "Berechnete Rückgabe",
    "available_cars":    "In diesem Zeitraum verfügbare Fahrzeuge",
    "no_cars":           "Keine Fahrzeuge für diesen Zeitraum frei.",
    "select_car":        "Fahrzeug auswählen",
    "quick_register":    "Schnelle Mieterfassung",
    "quick_register_help":"Geben Sie die Kundendaten ein. Die Summe aktualisiert sich live, wenn Sie den Tarif ändern.",
    "client_name":       "Vollständiger Name des Kunden",
    "client_phone":      "Telefon / WhatsApp",
    "client_id":         "Ausweis- / Reisepassnummer",
    "negotiated_rate":   "Vereinbarter Tagestarif",
    "negotiated_rate_help":"Standardmäßig der Listenpreis. Ändern Sie ihn — die Summe aktualisiert sich live.",
    "deposit":           "Erhaltene Kaution",
    "live_total":        "Aktuelle Summe",
    "register_btn":      "Miete speichern",
    "register_ok":       "Miete gespeichert",
    "register_need_fields":"Kundenname und Telefon sind erforderlich.",
    # fleet table
    "fleet_title":       "Gesamte Flotte",
    "fleet_help":        "Alle Fahrzeuge. Suche nach Marke, Kennzeichen oder Code.",
    "search":            "Suchen…",
    "col_id":            "Fahrzeugcode",
    "col_model":         "Marke / Modell",
    "col_year":          "Jahr",
    "col_plate":         "Kennzeichen",
    "col_color":         "Farbe",
    "col_mileage":       "Kilometerstand",
    "col_status":        "Status",
    "col_rate":          "Tagestarif",
    "col_notes":         "Notizen",
    "col_count":         "Fahrzeuge",
    # status labels
    "Available":         "Verfügbar",
    "Rented":            "Vermietet",
    "In Garage":         "In Werkstatt",
    "Maintenance":       "Wartung",
    "DELETED":           "Archiviert",
    # fleet CRUD
    "fleet_add":         "Fahrzeug hinzufügen",
    "fleet_edit":        "Fahrzeug bearbeiten",
    "fleet_delete":      "Löschen / Archivieren",
    "fleet_add_help":    "Der Fahrzeugcode wird automatisch vergeben.",
    "fleet_edit_help":   "Wählen Sie das zu aktualisierende Fahrzeug.",
    "fleet_delete_help": "Administrator kann archivieren; Super-Administrator kann dauerhaft löschen.",
    "add_btn":           "Hinzufügen",
    "update_btn":        "Aktualisieren",
    "added_ok":          "Fahrzeug hinzugefügt.",
    "updated_ok":        "Fahrzeug aktualisiert.",
    "soft_delete":       "Archivieren",
    "hard_delete":       "Dauerhaft löschen",
    "delete_confirm":    "Ich bestätige diese Aktion",
    "soft_deleted_done": "Fahrzeug archiviert.",
    "hard_deleted_done": "Fahrzeug dauerhaft gelöscht.",
    "archived_list":     "Archivierte Fahrzeuge",
    "select_vehicle":    "Fahrzeug auswählen",
    "restore_btn":       "Wiederherstellen",
    "restored_ok":       "Fahrzeug in die aktive Flotte zurückgeholt.",
    # reservations
    "reservations_title":"Reservierungen",
    "reservations_help": "Mietverträge erstellen, anzeigen und stornieren.",
    "active_reservations":"Aktive Mietverträge",
    "no_active_reservations":"Keine aktiven Mietverträge.",
    "search_active":     "Aktive Mietverträge suchen…",
    "no_search_results": "Keine Mietverträge entsprechen Ihrer Suche.",
    "cancel_btn":        "Stornieren",
    "cancel_done":       "Miete storniert.",
    "col_customer":      "Kunde",
    "col_car":           "Fahrzeug",
    "col_period":        "Zeitraum",
    "col_deal":          "Vertrag",
    "col_days":          "Tage",
    "col_total":         "Gesamt",
    "col_deposit":       "Kaution",
    "col_overdue":       "Überfällig",
    "no_create_perm":    "Sie benötigen mindestens die Rolle Agent, um Mietverträge zu erstellen.",
    "overdue_badge":     "ÜBERFÄLLIG",
    "overdue_detail":    "{h:.0f} Std. verspätet",
    # customers
    "customers_title":   "Kundenverzeichnis",
    "card_open":         "Öffnen",
    "open_full_table":   "Vollständige Tabelle öffnen",
    "customers_help":    "Alle registrierten Kunden und ihre Miethistorie.",
    "customer_search":   "Kunden suchen…",
    "col_rentals":       "Mietverträge",
    "col_last_rental":   "Letzte Miete",
    "col_phone":         "Telefon",
    "col_idno":          "Ausweis / Reisepass",
    "no_customers":      "Noch keine Kunden.",
    "customer_history":  "Miethistorie",
    # finance
    "finance_title":     "Finanzen",
    "finance_help":      "Einnahmeposten und Aufschlüsselung pro Fahrzeug.",
    "total_revenue":     "Gesamteinnahmen",
    "rental_revenue":    "Mieteinnahmen",
    "penalty_revenue":   "Verspätungsstrafen",
    "damage_revenue":    "Schadensersatz",
    "by_vehicle":        "Einnahmen pro Fahrzeug",
    "no_finance_data":   "Noch keine Finanzaktivität.",
    "monthly_chart":     "Monatliche Einnahmen",
    "col_income":        "Einnahmen",
    # settings
    "settings_title":    "Einstellungen",
    "settings_help":     "Unternehmensdaten, Benutzerverwaltung und Passwort.",
    "tab_business":      "Unternehmen",
    "tab_users":         "Benutzer",
    "tab_password":      "Passwort",
    "business_settings": "Unternehmensdaten",
    "business_name":     "Unternehmensname",
    "business_name_help":"Wird in der oberen Leiste und im Anmeldebildschirm angezeigt.",
    "business_saved":    "Unternehmensdaten aktualisiert.",
    "save_btn":          "Speichern",
    "user_management":   "Benutzerverwaltung",
    "create_user":       "Neuer Benutzer",
    "full_name":         "Vollständiger Name",
    "add_user_btn":      "Benutzer hinzufügen",
    "user_created":      "Benutzer erstellt.",
    "user_deleted":      "Benutzer gelöscht.",
    "cannot_delete_self": "Sie können Ihr eigenes Konto nicht löschen.",
    "users_list":        "Vorhandene Benutzer",
    "active":            "Aktiv",
    "deactivate":        "Deaktivieren",
    "inactive":          "Inaktiv",
    "activate":          "Aktivieren",
    "change_role":       "Rolle ändern",
    "role_updated":      "Rolle aktualisiert.",
    "change_password":   "Passwort ändern",
    "current_password":  "Aktuelles Passwort",
    "new_password":      "Neues Passwort",
    "confirm_password":  "Neues Passwort (erneut)",
    "pw_changed":        "Passwort aktualisiert.",
    "pw_mismatch":       "Die neuen Passwörter stimmen nicht überein.",
    "fields_required":   "Bitte füllen Sie alle Pflichtfelder aus.",
    "role_not_allowed":  "Sie dürfen diese Rolle nicht zuweisen.",
    "password_too_short":"Das Passwort muss mindestens 6 Zeichen lang sein.",
    "user_exists":       "Dieser Benutzername existiert bereits.",
    "wrong_current":     "Das aktuelle Passwort ist falsch.",
    "manage_rental":     "Verwalten / Rückgabe",
    "return_btn":        "Rückgabe bearbeiten & abschließen",
    "late_fee":          "Verspätungsstrafe",
    "damage_charge":     "Schadensgebühr",
    "return_notes":      "Rückgabe- / Zustandsnotizen",
    "contract_signed":   "Vertrag unterschrieben",
    "return_done":       "Fahrzeug zurückgegeben und Miete abgeschlossen.",
    # finance — costs & evaluation
    "fin_tab_overview":  "Übersicht",
    "fin_tab_monthly":   "Monatlich",
    "fin_tab_yearly":    "Jährlich",
    "fin_tab_vehicle":   "Nach Fahrzeug",
    "fin_tab_customer":  "Nach Kunde",
    "fin_tab_costs":     "Kosten",
    "by_customer_revenue":"Einnahmen pro Kunde",
    "download_csv":      "CSV herunterladen",
    "download_pdf":      "PDF herunterladen",
    "download_timeline": "Zeitachse herunterladen (PDF)",
    "report_metric":     "Kennzahl",
    "total_cost":        "Gesamtkosten",
    "net_profit":        "Nettogewinn",
    "profit_margin":     "Gewinnmarge",
    "income_vs_cost":    "Einnahmen & Kosten",
    "monthly_eval":      "Monatlich Einnahmen / Kosten / Netto",
    "yearly_eval":       "Jährlich Einnahmen / Kosten / Netto",
    "col_cost":          "Kosten",
    "col_net":           "Netto",
    "col_year":          "Jahr",
    "by_vehicle_profit": "Rentabilität pro Fahrzeug",
    "cost_breakdown":    "Kosten nach Art",
    "add_cost_section":  "Fahrzeugkosten hinzufügen",
    "cost_type":         "Kostenart",
    "cost_amount":       "Betrag",
    "cost_date":         "Datum",
    "cost_note":         "Notiz",
    "add_cost_btn":      "Kosten hinzufügen",
    "cost_added":        "Kosten erfasst.",
    "recent_costs":      "Letzte Kosten",
    "no_costs":          "Noch keine Kosten erfasst.",
    "delete_btn":        "Löschen",
    "cost_insurance":    "Versicherung",
    "cost_maintenance":  "Wartung / Reparatur",
    "cost_depreciation": "Abschreibung",
    "cost_fuel":         "Kraftstoff",
    "cost_financing":    "Finanzierung / Kredit",
    "cost_registration": "Zulassung / Steuer",
    "cost_other":        "Sonstiges",
    # invoice
    "invoice_heading":   "RECHNUNG",
    "bill_to":           "Rechnungsempfänger",
    "invoice_no":        "Rechnungsnr.",
    "invoice_date":      "Datum",
    "invoice_vehicle":   "Fahrzeug",
    "invoice_period":    "Mietzeitraum",
    "invoice_desc":      "Beschreibung",
    "invoice_qty":       "Tage",
    "invoice_unit":      "Stückpreis",
    "invoice_amount":    "Betrag",
    "invoice_line_rental":"Fahrzeugmiete",
    "invoice_line_deposit":"Kaution",
    "invoice_subtotal":  "Zwischensumme",
    "invoice_total":     "GESAMTSUMME",
    "invoice_balance":   "Offener Betrag",
    "invoice_thanks":    "Vielen Dank für Ihr Vertrauen.",
    "invoice_print":     "🖨️ Rechnung drucken",
    "invoice_download":  "⬇️ Rechnung herunterladen (PDF)",
    "invoice_ready":     "Rechnung bereit — drucken oder unten herunterladen.",
    "invoice_signed":    "Vertrag unterschrieben",
    "invoice_unsigned":  "Vertrag nicht unterschrieben",
    "invoice_footer":    "Dieses Dokument wurde maschinell erstellt.",
    "show_invoice":      "🧾 Rechnung erstellen / anzeigen",
    # activity log
    "tab_activity":      "Aktivität",
    "activity_log":      "Aktivitätsprotokoll",
    "no_activity":       "Noch keine Aktivität erfasst.",
    "col_when":          "Wann",
    "col_user":          "Benutzer",
    "col_action":        "Aktion",
    "col_entity":        "Objekt",
    "col_detail":        "Detail",
    "close_btn":         "Schließen",
    # reservation creator / customer registrar
    "invoice_issued_by": "Mitarbeitername",
    "col_registered_by": "Registriert von",
    # return reminders (due-soon alert / overdue alarm)
    "due_soon_badge":    "BALD FÄLLIG",
    "due_soon_detail":   "{h:.0f} Std. übrig",
    "notif_overdue_title":  "Überfällige Rückgaben",
    "notif_due_soon_title": "Rückgaben fällig innerhalb von {n} Std.",
    "notif_overdue_by":  "{h:.0f} Std. überfällig",
    "notif_due_in":      "in {h:.0f} Std.",
    # language preference (Settings)
    "tab_language":      "Sprache",
    "language_help":     "Ihre Oberflächensprache wird gespeichert und bei der nächsten Anmeldung wieder verwendet.",
    "lang_saved":        "Spracheinstellung gespeichert.",
    # admin account management
    "manage_account":    "Konto verwalten",
    "change_username":   "Benutzernamen ändern",
    "username_changed":  "Benutzername aktualisiert.",
    "reset_password":    "Passwort zurücksetzen",
    "pw_reset_done":     "Passwort zurückgesetzt.",
    # vehicle photos
    "vehicle_photo":         "Fahrzeugfoto (optional)",
    "vehicle_photo_help":    "Optional — JPG/PNG/WEBP. Kann später hinzugefügt werden.",
    "vehicle_photo_replace": "Foto ersetzen (optional)",
    "vehicle_photo_remove":  "Aktuelles Foto entfernen",
    "vehicle_photos":        "Fahrzeugfotos (optional)",
    "manage_photos":         "Fotos verwalten",
    "no_photos":             "Noch keine Fotos.",
    "add_photos":            "Fotos hinzufügen",
    "photos_added":          "Fotos hinzugefügt.",
    "available_now":         "Jetzt verfügbar",
    "no_available_now":      "Derzeit keine Fahrzeuge verfügbar.",
    "per_day":               "Tag",
    # customer edit / invoice / reassign
    "edit_customer":         "Kundendaten bearbeiten",
    "customer_saved":        "Kundendaten aktualisiert.",
    "print_invoice":         "Rechnung drucken",
    "choose_client_language": "Sprache des Kunden wählen",
    "reassign_registered_by": "Registriert-von neu zuweisen",
    "apply_btn":             "Anwenden",
    "registered_by_updated": "Registriert-von aktualisiert.",
    # rental popup + invoice language/terms
    "open_rental_btn":       "Miete erfassen",
    "rent_card_btn":         "Mieten",
    "invoice_language":      "Rechnungssprache",
    "not_available_window":  "Dieses Fahrzeug ist für die ausgewählten Daten nicht verfügbar.",
    "invoice_terms_heading": "Allgemeine Geschäftsbedingungen",
    # notification bell + whatsapp
    "notifications_title":   "Erinnerungen",
    "no_reminders":          "Derzeit keine Erinnerungen.",
    "whatsapp_msg":          "WhatsApp",
    "whatsapp_call":         "Anrufen",
    "phone_copy_hint":       "Tippen Sie auf das Kopiersymbol, um die Nummer zu kopieren:",
    "wa_reminder":           "Hallo {name}, Ihre Miete für {car} ist am {due} fällig. Bitte geben Sie das Fahrzeug pünktlich zurück. Vielen Dank.",
    # license / annual unlock
    "tab_license":           "Lizenz",
    "license_help":          "Jährliche Lizenzverwaltung. Kalender sind auf das lizenzierte Jahr begrenzt.",
    "license_status":        "Lizenziert bis {y}.",
    "unlock_next_year":      "{y} freischalten",
    "year_unlocked":         "Jahr freigeschaltet.",
    "generate_license_invoice": "Lizenzrechnung erstellen",
    "license_invoice_title": "Softwarelizenz-Rechnung",
    "license_licensee":      "Lizenznehmer",
    "license_product":       "Produkt",
    "license_period":        "Lizenzzeitraum",
    "license_years":         "Jahre",
    "license_amount":        "Betrag",
    "license_purchase_date": "Kaufdatum",
    "notif_license_title":   "Lizenzverlängerung",
    "notif_license_msg":     "Ihre Lizenz läuft am {date} ab ({days} Tage verbleibend). Bitte verlängern.",
    # SMTP
    "smtp_settings":         "E-Mail-Einstellungen (SMTP)",
    "smtp_help":             "Für E-Mails zur Passwortwiederherstellung. Kann vorerst leer bleiben.",
    "smtp_configured":       "Konfiguriert",
    "smtp_not_set":          "Nicht konfiguriert (neues Passwort wird auf dem Bildschirm angezeigt)",
    "smtp_from":             "Absenderadresse",
    # profile email
    "my_profile":            "Mein Profil",
    "email_label":           "E-Mail",
    "email_help":            "Wird für die Passwortwiederherstellung verwendet.",
    "email_saved":           "E-Mail gespeichert.",
    "reset_password_help":   "Erzeugt ein neues Passwort und sendet es per E-Mail (zeigt es auf dem Bildschirm an, wenn kein SMTP eingerichtet ist).",
    # password recovery
    "forgot_password":       "Passwort vergessen",
    "recover_help":          "Für Administrator- / Super-Administrator-Konten. Andere Benutzer sollten sich an ihren Administrator wenden.",
    "recover_btn":           "Zurücksetzen & neues Passwort per E-Mail senden",
    "recover_sent":          "Ein neues Passwort wurde an {to} gesendet.",
    "recover_fallback":      "SMTP nicht konfiguriert. Neues Passwort: {pw} (wäre an {to} gesendet worden).",
    "recover_admin_only":    "Diese Funktion ist nur für Administrator / Super-Administrator verfügbar.",
    # activity masking + filter
    "filter_action":         "Nach Aktion filtern",
    "filter_by":             "Filtern nach",
    "status_locked_rented":  "Der Status ist gesperrt, während dieses Fahrzeug aktiv vermietet ist.",
    "system_admin_label":    "Systemadministrator",
    # company logo / profile / licenses / vehicle status
    "company_logo":          "Firmenlogo",
    "logo_help":             "Erscheint auf jeder Rechnung. PNG/JPG; wird passend verkleinert.",
    "upload_logo":           "Logo hochladen",
    "remove_logo":           "Logo entfernen",
    "logo_saved":            "Logo gespeichert.",
    "logo_removed":          "Logo entfernt.",
    # company stamp (invoice signature seal) + invoice signature lines
    "company_stamp":         "Firmenstempel",
    "stamp_help":            "Erscheint im Unterschriftsbereich jeder Rechnung (als Firmensiegel). PNG/JPG; wird passend verkleinert.",
    "upload_stamp":          "Stempel hochladen",
    "remove_stamp":          "Stempel entfernen",
    "stamp_saved":           "Stempel gespeichert.",
    "stamp_removed":         "Stempel entfernt.",
    "invoice_customer_signature":   "Unterschrift des Kunden",
    "invoice_authorized_signature": "Autorisierte Unterschrift",
    # business contact + invoice quick-links QR buttons
    "business_contact":      "Geschäftskontakt & Rechnungs-QR",
    "contact_help":          "Wird für die QR-Schnelllink-Schaltflächen der Rechnung verwendet (WhatsApp, Kontaktkarte, Wegbeschreibung).",
    "business_phone":        "Geschäftstelefon",
    "business_address":      "Geschäftsadresse",
    "business_maps_url":     "Karten- / Routenlink (optional)",
    "business_email":        "Geschäfts-E-Mail (optional)",
    "contact_saved":         "Kontaktdaten gespeichert.",
    "pay_qr_enable":         "Bezahl-QR (Banküberweisung) auf Rechnungen aktivieren",
    "pay_qr_help":           "Fügt einen SEPA-Überweisungs-QR-Code für den offenen Betrag hinzu. Erfordert die IBAN unten.",
    "business_iban":         "IBAN",
    "invoice_quick_links":   "Schnelllinks — Scannen",
    "qr_pay":                "Restbetrag zahlen",
    "qr_whatsapp":           "WhatsApp schreiben",
    "qr_contact":            "Kontakt speichern",
    "qr_location":           "Finden / zurückgeben",
    "qr_summary":            "Mietübersicht",
    "qr_scan_hint":          "Mit dem Handy scannen",
    # theme customization (super-admin) + night mode
    "select_theme":          "Thema wählen",
    "theme_font":            "Schriftart",
    "theme_primary":         "Primärfarbe",
    "theme_secondary":       "Sekundärfarbe",
    "theme_success":         "Erfolgsfarbe",
    "theme_warning":         "Warnfarbe",
    "theme_alert":           "Alarmfarbe",
    "theme_disabled":        "Deaktiviert-Farbe",
    "theme_bg":              "Hintergrundfarbe",
    "theme_saved":           "Thema gespeichert.",
    "theme_reset":           "Auf Standard zurücksetzen",
    "theme_help":            "Schriftart und Markenfarben wählen. Gilt für alle Benutzer.",
    "night_mode":            "Nachtmodus",
    "day_mode":              "Tagmodus",
    "tab_profile":           "Profil",
    "profile_saved":         "Profil aktualisiert.",
    "license_records":       "Lizenzeinträge",
    "add_license":           "Lizenz hinzufügen",
    "edit_license":          "Lizenz bearbeiten",
    "delete_license":        "Lizenz löschen",
    "license_added":         "Lizenz hinzugefügt.",
    "license_updated":       "Lizenz aktualisiert.",
    "license_deleted":       "Lizenz gelöscht.",
    "no_licenses":           "Noch keine Lizenzeinträge.",
    "col_actions":           "Aktionen",
    "to_garage":             "In die Garage",
    "to_maintenance":        "In die Wartung",
    "to_available":          "Verfügbar machen",
    "status_updated":        "Status aktualisiert.",
    "edit_btn":              "Bearbeiten",
    "last_super_admin":      "Der letzte Super-Administrator kann nicht entfernt werden.",
    # finance totals + year lock + return activity (v3.0 round 4)
    "fin_totals":            "Summen",
    "set_licensed_year_label":"Lizenzjahr festlegen",
    "licensed_year_saved":   "Lizenzjahr aktualisiert.",
    "return_activity":       "Aktion zurücksetzen",
    "activity_returned":     "Aktion zurückgesetzt.",
    "return_activity_help":  "Archivierte Fahrzeuge und stornierte Mieten wiederherstellen.",
    # customers split (round 5)
    "active_renters":        "Aktive Mieter",
    "no_active_renters":     "Derzeit mietet kein Kunde.",
    "all_customers":         "Alle Kunden",
    "open_customer":         "Kunde öffnen",
    # reset data + visitor hero — round 6
    "danger_zone":           "Gefahrenzone",
    "reset_finance_btn":     "Finanzdaten zurücksetzen",
    "reset_fleet_btn":       "Flottendaten zurücksetzen",
    "reset_finance_help":    "Löscht alle Einnahmen- (Belastungen) und Kostendatensätze. Fahrzeuge und Mieten bleiben erhalten.",
    "reset_fleet_help":      "Löscht alle Fahrzeuge, Fotos, Mieten und deren Finanzdaten. Kunden bleiben erhalten. Die Standardflotte wird beim nächsten Neustart neu geladen.",
    "reset_confirm_label":   "Zur Bestätigung RESET eingeben",
    "reset_done":            "Daten zurückgesetzt.",
    "visitor_hero":          "Verfügbare Fahrzeuge entdecken",
    "visitor_hero_sub":      "Wählen Sie das passende Fahrzeug aus unserer Flotte. Kontaktieren Sie unser Team zur Buchung.",
    "contact_to_book":       "Kontaktieren Sie uns zum Buchen",
    # sidebar toggle (round 7)
    "open_sidebar":          "Seitenleiste öffnen",
    "collapse_sidebar":      "Seitenleiste einklappen",
    # data management — delete finance / client records (round 8)
    "tab_data":              "Daten",
    "data_help":             "Einzelne Finanz- oder Kundendatensätze löschen oder alle entfernen. Nur Super-Administrator.",
    "finance_records_section":"Finanzdatensätze",
    "client_records_section": "Kundendatensätze",
    "income_records":        "Einnahmen (Belastungen)",
    "expense_records":       "Ausgaben (Kosten)",
    "no_finance_records":    "Keine Finanzdatensätze.",
    "col_type":              "Art",
    "charge_rental":         "Miete",
    "charge_overdue_penalty":"Verspätungsstrafe",
    "charge_damage":         "Schaden",
    "charge_deposit":        "Kaution",
    "charge_refund":         "Rückerstattung",
    "record_deleted":        "Datensatz gelöscht.",
    "client_deleted":        "Kunde und seine Mieten gelöscht.",
    "delete_client_help":    "Löscht diesen Kunden mitsamt seinen Mietverträgen und Belastungen dauerhaft.",
    "reset_clients_btn":     "Kundendaten zurücksetzen",
    "reset_clients_help":    "Löscht alle Kunden mit ihren Mieten und den zugehörigen Belastungen. Fahrzeuge bleiben erhalten und werden freigegeben.",
    # edit reservation + finance reports / month drill-down (v3.1)
    "edit_reservation":      "Reservierung bearbeiten",
    "change_car":            "Fahrzeug wechseln",
    "keep_current_car":      "Aktuelles Fahrzeug behalten",
    "rental_updated":        "Reservierung aktualisiert.",
    "select_month":          "Monat auswählen",
    "all_months":            "Alle Monate",
    "month_detail":          "Monatsdetail",
    "report_total":          "GESAMT",
    "report_generated":      "Erstellt",
    "report_period":         "Zeitraum",
    "report_business":       "Unternehmen",
    # duplicated invoice copies (customer + office)
    "invoice_copy_customer": "Kundenexemplar",
    "invoice_copy_office":   "Büroexemplar",
    # add-reservation modal + timeline export range (v3.2)
    "add_reservation":       "Reservierung hinzufügen",
    "tl_export_range":       "Exportbereich",
    "tl_range_week":         "Diese Woche",
    "tl_range_month":        "Dieser Monat",
    "tl_range_year":         "Dieses Jahr",
    "tl_range_two":          "Zwei-Monats-Bereich",
    "tl_range_all":          "Alle Monate (separate Seiten)",
    "tl_pick_start_month":   "Startmonat",
    # timeline view buttons + show-done toggle (v3.3)
    "view_day":              "Tag",
    "view_week":             "Woche",
    "view_month":            "Monat",
    "view_year":             "Jahr",
    "view_today":            "Heute",
    "show_done":             "Erledigte anzeigen",
}

TERMS = {
    "title": "FAHRZEUGMIETBEDINGUNGEN & SCHADENSHAFTUNG",
    "rules": [
        "Das Fahrzeug muss gemäß den Verkehrsregeln benutzt werden. Die Einhaltung der Geschwindigkeitsbegrenzungen ist verpflichtend.",
        "Gemäß Firmenrichtlinie beträgt die maximale Betriebsgeschwindigkeit der Fahrzeuge 120 km/h. Bei Überschreitung der Grenze von 120 km/h haftet der Kunde für jeden durch überhöhte Geschwindigkeit verursachten Motor-, Turbo-, Getriebe- oder mechanischen Schaden. Die GPS-Daten und Geschwindigkeitsaufzeichnungen des Fahrzeugs werden als gültiger Nachweis anerkannt.",
        "Das Rauchen im Fahrzeug ist strengstens untersagt. Reinigungs-, Reparatur- oder Ersatzkosten für Zigarettengeruch, Brandflecken oder Sitz-/Polsterschäden werden dem Kunden berechnet.",
        "Schäden an Sitzen, Polstern, Kunststoffteilen, dem Multimediabildschirm oder der Innenausstattung werden vom Kunden getragen.",
        "Schäden durch Reifenplatzer, verbogene Felgen, Anfahren eines Bordsteins, unsachgemäßen Gebrauch oder Unachtsamkeit liegen in der Verantwortung des Kunden.",
        "Risse und Steinschläge an Windschutzscheibe, Scheinwerfern, Spiegeln oder Fenstern werden bei Bedienungsfehler oder Fahrlässigkeit vom Kunden getragen.",
        "Alle Kosten, die durch die Verwendung des falschen Kraftstoffs entstehen, werden dem Kunden berechnet.",
        "Bei Verlust, Bruch oder Beschädigung des Fahrzeugschlüssels werden die Kosten für einen neuen Schlüssel, Software und Abschleppen dem Kunden berechnet.",
        "Verkehrsstrafen, Autobahnmautgebühren, Parkstrafen und Durchfahrtsgebühren sind vom Mieter zu tragen.",
        "Bei der Übergabe werden Video- und Fotoaufnahmen gemacht. Der Zustand des Fahrzeugs bei der Übergabe wird als offizielle Aufzeichnung anerkannt.",
        "Das Unternehmen verwendet aus Sicherheits- und Flottenmanagementgründen ein Fahrzeugortungssystem (GPS).",
        "Das Fahrzeug muss mit demselben Kraftstoffstand zurückgegeben werden, mit dem es übernommen wurde.",
        "Verspätete Rückgabe: Das Fahrzeug muss zum vereinbarten Datum und zur vereinbarten Uhrzeit zurückgegeben werden. Jeder angefangene Tag der Verspätung wird als voller zusätzlicher Miettag berechnet; zusätzlich kann eine Strafgebühr für verspätete Rückgabe anfallen.",
    ],
}
