"""Italian (Italiano) translations — auto-generated for Balkan Car Rentals v3.0.
UI mirrors config/i18n.py's English block key-for-key; TERMS mirrors config/terms.py."""

UI = {
    "nav_dashboard":     "Home",
    "nav_reservations":  "Prenotazioni",
    "nav_fleet":         "Flotta",
    "nav_customers":     "Clienti",
    "nav_finance":       "Finanze",
    "nav_settings":      "Impostazioni",
    "language":          "Lingua",
    "coming_soon":       "Prossimamente.",
    "now_label":         "ORA",
    # auth
    "login_title":       "Accesso sicuro",
    "login_username":    "Nome utente",
    "login_password":    "Password",
    "login_remember":    "Ricordami (30 giorni)",
    "login_btn":         "Accedi",
    "login_failed":      "Nome utente/password errati o account non attivo.",
    "logout":            "Esci",
    "signed_in_as":      "Accesso:",
    "default_admin_warning": "Accesso predefinito admin/admin — cambiarlo subito nelle Impostazioni.",
    "access_denied":     "Non hai i permessi per visualizzare questa pagina.",
    # roles
    "role_super_admin":  "Super Amministratore",
    "role_admin":        "Amministratore",
    "role_employer":     "Agente",
    "role_visitor":      "Visitatore",
    "role":              "Ruolo",
    # dashboard
    "dashboard_title":   "Panoramica",
    "dashboard_help":    "Stato della flotta in tempo reale e cronologia dei noleggi.",
    "timeline_title":    "Cronologia di occupazione della flotta",
    "timeline_help":     "Ogni riga è un veicolo. Passa sopra un blocco per vedere il cliente. Linea verticale = ora.",
    "timeline_empty":    "Nessun noleggio attivo al momento.",
    "kpi_total":         "Veicoli totali",
    "kpi_available":     "Disponibili",
    "kpi_rented":        "Noleggiati",
    "kpi_garage":        "In garage / Manutenzione",
    # availability
    "availability_title":"Disponibilità e calcolo del rientro",
    "availability_help": "Scegli una data e un'ora; l'app calcola il momento del rientro.",
    "start_date":        "Data di inizio",
    "start_time":        "Ora di ritiro",
    "days":              "Numero di giorni",
    "return_time":       "Ora di rientro",
    "return_date":       "Data di rientro",
    "calculated_return": "Rientro calcolato",
    "available_cars":    "Auto disponibili in questa finestra",
    "no_cars":           "Nessuna auto libera per questa finestra.",
    "select_car":        "Seleziona un veicolo",
    "quick_register":    "Registrazione rapida del noleggio",
    "quick_register_help":"Inserisci i dati del cliente. Il totale si aggiorna in tempo reale al variare della tariffa.",
    "client_name":       "Nome e cognome del cliente",
    "client_phone":      "Telefono / WhatsApp",
    "client_id":         "Documento / N. passaporto",
    "negotiated_rate":   "Tariffa giornaliera concordata",
    "negotiated_rate_help":"Predefinita al prezzo di listino. Modificala — il totale si aggiorna in tempo reale.",
    "deposit":           "Cauzione ricevuta",
    "live_total":        "Totale attuale",
    "register_btn":      "Salva noleggio",
    "register_ok":       "Noleggio salvato",
    "register_need_fields":"Nome e telefono del cliente sono obbligatori.",
    # fleet table
    "fleet_title":       "Intera flotta",
    "fleet_help":        "Tutti i veicoli. Cerca per marca, targa o codice.",
    "search":            "Cerca…",
    "col_id":            "Codice veicolo",
    "col_model":         "Marca / Modello",
    "col_year":          "Anno",
    "col_plate":         "Targa",
    "col_color":         "Colore",
    "col_mileage":       "Chilometraggio",
    "col_status":        "Stato",
    "col_rate":          "Tariffa giornaliera",
    "col_notes":         "Note",
    "col_count":         "veicoli",
    # status labels
    "Available":         "Disponibile",
    "Rented":            "Noleggiato",
    "In Garage":         "In garage",
    "Maintenance":       "Manutenzione",
    "DELETED":           "Archiviato",
    # fleet CRUD
    "fleet_add":         "Aggiungi veicolo",
    "fleet_edit":        "Modifica veicolo",
    "fleet_delete":      "Elimina / Archivia",
    "fleet_add_help":    "Il codice veicolo viene assegnato automaticamente.",
    "fleet_edit_help":   "Seleziona il veicolo da aggiornare.",
    "fleet_delete_help": "L'Amministratore può archiviare; il Super Amministratore può eliminare definitivamente.",
    "add_btn":           "Aggiungi",
    "update_btn":        "Aggiorna",
    "added_ok":          "Veicolo aggiunto.",
    "updated_ok":        "Veicolo aggiornato.",
    "soft_delete":       "Archivia",
    "hard_delete":       "Elimina definitivamente",
    "delete_confirm":    "Confermo questa azione",
    "soft_deleted_done": "Veicolo archiviato.",
    "hard_deleted_done": "Veicolo eliminato definitivamente.",
    "archived_list":     "Veicoli archiviati",
    "select_vehicle":    "Seleziona un veicolo",
    "restore_btn":       "Ripristina",
    "restored_ok":       "Veicolo ripristinato nella flotta attiva.",
    # reservations
    "reservations_title":"Prenotazioni",
    "reservations_help": "Crea, visualizza e annulla i noleggi.",
    "active_reservations":"Noleggi attivi",
    "no_active_reservations":"Nessun noleggio attivo.",
    "search_active":     "Cerca noleggi attivi…",
    "no_search_results": "Nessun noleggio corrisponde alla ricerca.",
    "cancel_btn":        "Annulla",
    "cancel_done":       "Noleggio annullato.",
    "col_customer":      "Cliente",
    "col_car":           "Veicolo",
    "col_period":        "Periodo",
    "col_deal":          "Contratto",
    "col_days":          "Giorni",
    "col_total":         "Totale",
    "col_deposit":       "Cauzione",
    "col_overdue":       "In ritardo",
    "no_create_perm":    "È necessario almeno il ruolo Agente per creare noleggi.",
    "overdue_badge":     "IN RITARDO",
    "overdue_detail":    "{h:.0f} h di ritardo",
    # customers
    "customers_title":   "Rubrica clienti",
    "card_open":         "Apri",
    "open_full_table":   "Apri tabella completa",
    "customers_help":    "Tutti i clienti registrati e la loro cronologia di noleggi.",
    "customer_search":   "Cerca clienti…",
    "col_rentals":       "Noleggi",
    "col_last_rental":   "Ultimo noleggio",
    "col_phone":         "Telefono",
    "col_idno":          "Documento / Passaporto",
    "no_customers":      "Ancora nessun cliente.",
    "customer_history":  "Cronologia noleggi",
    # finance
    "finance_title":     "Finanze",
    "finance_help":      "Voci di ricavo e ripartizione per veicolo.",
    "total_revenue":     "Ricavo totale",
    "rental_revenue":    "Ricavo da noleggi",
    "penalty_revenue":   "Penali per ritardo",
    "damage_revenue":    "Recupero danni",
    "by_vehicle":        "Ricavo per veicolo",
    "no_finance_data":   "Ancora nessuna attività finanziaria.",
    "monthly_chart":     "Ricavo mensile",
    "col_income":        "Ricavo",
    # settings
    "settings_title":    "Impostazioni",
    "settings_help":     "Dati aziendali, gestione utenti e password.",
    "tab_business":      "Azienda",
    "tab_users":         "Utenti",
    "tab_password":      "Password",
    "business_settings": "Dati aziendali",
    "business_name":     "Nome dell'azienda",
    "business_name_help":"Mostrato nella barra superiore e nella schermata di accesso.",
    "business_saved":    "Dati aziendali aggiornati.",
    "save_btn":          "Salva",
    "user_management":   "Gestione utenti",
    "create_user":       "Nuovo utente",
    "full_name":         "Nome e cognome",
    "add_user_btn":      "Aggiungi utente",
    "user_created":      "Utente creato.",
    "user_deleted":      "Utente eliminato.",
    "cannot_delete_self": "Non puoi eliminare il tuo account.",
    "users_list":        "Utenti esistenti",
    "active":            "Attivo",
    "deactivate":        "Disattiva",
    "inactive":          "Inattivo",
    "activate":          "Attiva",
    "change_role":       "Cambia ruolo",
    "role_updated":      "Ruolo aggiornato.",
    "change_password":   "Cambia password",
    "current_password":  "Password attuale",
    "new_password":      "Nuova password",
    "confirm_password":  "Nuova password (di nuovo)",
    "pw_changed":        "Password aggiornata.",
    "pw_mismatch":       "Le nuove password non corrispondono.",
    "fields_required":   "Compila tutti i campi obbligatori.",
    "role_not_allowed":  "Non sei autorizzato ad assegnare quel ruolo.",
    "password_too_short":"La password deve contenere almeno 6 caratteri.",
    "user_exists":       "Questo nome utente esiste già.",
    "wrong_current":     "La password attuale non è corretta.",
    "manage_rental":     "Gestisci / Rientro",
    "return_btn":        "Elabora rientro e chiudi",
    "late_fee":          "Penale per ritardo",
    "damage_charge":     "Addebito danni",
    "return_notes":      "Note su rientro / condizioni",
    "contract_signed":   "Contratto firmato",
    "return_done":       "Veicolo rientrato e noleggio chiuso.",
    # finance — costs & evaluation
    "fin_tab_overview":  "Panoramica",
    "fin_tab_monthly":   "Mensile",
    "fin_tab_yearly":    "Annuale",
    "fin_tab_vehicle":   "Per veicolo",
    "fin_tab_customer":  "Per cliente",
    "fin_tab_costs":     "Costi",
    "by_customer_revenue":"Entrate per cliente",
    "download_csv":      "Scarica CSV",
    "download_pdf":      "Scarica PDF",
    "download_timeline": "Scarica Cronologia (PDF)",
    "report_metric":     "Voce",
    "total_cost":        "Costo totale",
    "net_profit":        "Utile netto",
    "profit_margin":     "Margine di profitto",
    "income_vs_cost":    "Entrate e costi",
    "monthly_eval":      "Entrate / Costi / Netto mensili",
    "yearly_eval":       "Entrate / Costi / Netto annuali",
    "col_cost":          "Costo",
    "col_net":           "Netto",
    "col_year":          "Anno",
    "by_vehicle_profit": "Redditività per veicolo",
    "cost_breakdown":    "Costi per tipo",
    "add_cost_section":  "Aggiungi costo veicolo",
    "cost_type":         "Tipo di costo",
    "cost_amount":       "Importo",
    "cost_date":         "Data",
    "cost_note":         "Nota",
    "add_cost_btn":      "Aggiungi costo",
    "cost_added":        "Costo registrato.",
    "recent_costs":      "Costi recenti",
    "no_costs":          "Ancora nessun costo registrato.",
    "delete_btn":        "Elimina",
    "cost_insurance":    "Assicurazione",
    "cost_maintenance":  "Manutenzione / Riparazione",
    "cost_depreciation": "Ammortamento",
    "cost_fuel":         "Carburante",
    "cost_financing":    "Finanziamento / Prestito",
    "cost_registration": "Immatricolazione / Tasse",
    "cost_other":        "Altro",
    # invoice
    "invoice_heading":   "FATTURA",
    "bill_to":           "Intestato a",
    "invoice_no":        "N. fattura",
    "invoice_date":      "Data",
    "invoice_vehicle":   "Veicolo",
    "invoice_period":    "Periodo di noleggio",
    "invoice_desc":      "Descrizione",
    "invoice_qty":       "Giorni",
    "invoice_unit":      "Prezzo unitario",
    "invoice_amount":    "Importo",
    "invoice_line_rental":"Noleggio veicolo",
    "invoice_line_deposit":"Cauzione",
    "invoice_subtotal":  "Subtotale",
    "invoice_total":     "TOTALE COMPLESSIVO",
    "invoice_balance":   "Saldo dovuto",
    "invoice_thanks":    "Grazie per averci scelto.",
    "invoice_print":     "🖨️ Stampa fattura",
    "invoice_download":  "⬇️ Scarica fattura (PDF)",
    "invoice_ready":     "Fattura pronta — stampala o scaricala qui sotto.",
    "invoice_signed":    "Contratto firmato",
    "invoice_unsigned":  "Contratto non firmato",
    "invoice_footer":    "Questo documento è stato generato dal computer.",
    "show_invoice":      "🧾 Crea / Visualizza fattura",
    # activity log
    "tab_activity":      "Attività",
    "activity_log":      "Registro attività",
    "no_activity":       "Ancora nessuna attività registrata.",
    "col_when":          "Quando",
    "col_user":          "Utente",
    "col_action":        "Azione",
    "col_entity":        "Entità",
    "col_detail":        "Dettaglio",
    "close_btn":         "Chiudi",
    # reservation creator / customer registrar
    "invoice_issued_by": "Nome dipendente",
    "col_registered_by": "Registrato da",
    # return reminders (due-soon alert / overdue alarm)
    "due_soon_badge":    "IN SCADENZA",
    "due_soon_detail":   "{h:.0f} h rimanenti",
    "notif_overdue_title":  "Rientri in ritardo",
    "notif_due_soon_title": "Rientri previsti entro {n} h",
    "notif_overdue_by":  "{h:.0f} h di ritardo",
    "notif_due_in":      "tra {h:.0f} h",
    # language preference (Settings)
    "tab_language":      "Lingua",
    "language_help":     "La lingua della tua interfaccia viene salvata e ricordata al tuo prossimo accesso.",
    "lang_saved":        "Preferenza di lingua salvata.",
    # admin account management
    "manage_account":    "Gestisci account",
    "change_username":   "Cambia nome utente",
    "username_changed":  "Nome utente aggiornato.",
    "reset_password":    "Reimposta password",
    "pw_reset_done":     "Password reimpostata.",
    # vehicle photos
    "vehicle_photo":         "Foto del veicolo (facoltativa)",
    "vehicle_photo_help":    "Facoltativa — JPG/PNG/WEBP. Può essere aggiunta in seguito.",
    "vehicle_photo_replace": "Sostituisci foto (facoltativa)",
    "vehicle_photo_remove":  "Rimuovi la foto attuale",
    "vehicle_photos":        "Foto del veicolo (facoltative)",
    "manage_photos":         "Gestisci foto",
    "no_photos":             "Ancora nessuna foto.",
    "add_photos":            "Aggiungi foto",
    "photos_added":          "Foto aggiunte.",
    "available_now":         "Disponibili ora",
    "no_available_now":      "Nessun veicolo disponibile al momento.",
    "per_day":               "giorno",
    # customer edit / invoice / reassign
    "edit_customer":         "Modifica dati cliente",
    "customer_saved":        "Dati cliente aggiornati.",
    "print_invoice":         "Stampa fattura",
    "choose_client_language": "Scegli la lingua del cliente",
    "reassign_registered_by": "Riassegna registrato da",
    "apply_btn":             "Applica",
    "registered_by_updated": "Registrato da aggiornato.",
    # rental popup + invoice language/terms
    "open_rental_btn":       "Registra noleggio",
    "rent_card_btn":         "Noleggia",
    "invoice_language":      "Lingua della fattura",
    "not_available_window":  "Questo veicolo non è disponibile per le date selezionate.",
    "invoice_terms_heading": "Termini e condizioni",
    # notification bell + whatsapp
    "notifications_title":   "Promemoria",
    "no_reminders":          "Nessun promemoria al momento.",
    "whatsapp_msg":          "WhatsApp",
    "whatsapp_call":         "Chiama",
    "phone_copy_hint":       "Tocca l'icona di copia per copiare il numero:",
    "wa_reminder":           "Salve {name}, il noleggio della tua {car} scade il {due}. Ti preghiamo di restituirla in tempo. Grazie.",
    # license / annual unlock
    "tab_license":           "Licenza",
    "license_help":          "Gestione della licenza annuale. I calendari sono limitati all'anno con licenza.",
    "license_status":        "Con licenza fino al {y}.",
    "unlock_next_year":      "Sblocca {y}",
    "year_unlocked":         "Anno sbloccato.",
    "generate_license_invoice": "Genera fattura della licenza",
    "license_invoice_title": "Fattura della licenza software",
    "license_licensee":      "Licenziatario",
    "license_product":       "Prodotto",
    "license_period":        "Periodo di licenza",
    "license_years":         "Anni",
    "license_amount":        "Importo",
    "license_purchase_date": "Data di acquisto",
    "notif_license_title":   "Rinnovo Licenza",
    "notif_license_msg":     "La tua licenza scade il {date} ({days} giorni rimanenti). Si prega di rinnovare.",
    # SMTP
    "smtp_settings":         "Impostazioni email (SMTP)",
    "smtp_help":             "Per le email di recupero password. Per ora può essere lasciato vuoto.",
    "smtp_configured":       "Configurato",
    "smtp_not_set":          "Non configurato (la nuova password viene mostrata sullo schermo)",
    "smtp_from":             "Indirizzo mittente",
    # profile email
    "my_profile":            "Il mio profilo",
    "email_label":           "Email",
    "email_help":            "Usata per il recupero della password.",
    "email_saved":           "Email salvata.",
    "reset_password_help":   "Genera una nuova password e la invia via email (la mostra sullo schermo se non c'è SMTP).",
    # password recovery
    "forgot_password":       "Password dimenticata",
    "recover_help":          "Per account Amministratore / Super Amministratore. Gli altri utenti devono rivolgersi al proprio amministratore.",
    "recover_btn":           "Reimposta e invia nuova password via email",
    "recover_sent":          "Una nuova password è stata inviata via email a {to}.",
    "recover_fallback":      "SMTP non configurato. Nuova password: {pw} (sarebbe stata inviata via email a {to}).",
    "recover_admin_only":    "Questa funzione è disponibile solo per Amministratore / Super Amministratore.",
    # activity masking + filter
    "filter_action":         "Filtra per azione",
    "filter_by":             "Filtra per",
    "status_locked_rented":  "Lo stato è bloccato mentre questo veicolo è a noleggio attivo.",
    "system_admin_label":    "amministratore di sistema",
    # company logo / profile / licenses / vehicle status
    "company_logo":          "Logo aziendale",
    "logo_help":             "Mostrato su ogni fattura. PNG/JPG; viene ridimensionato per adattarsi.",
    "upload_logo":           "Carica logo",
    "remove_logo":           "Rimuovi logo",
    "logo_saved":            "Logo salvato.",
    "logo_removed":          "Logo rimosso.",
    # company stamp (invoice signature seal) + invoice signature lines
    "company_stamp":         "Timbro aziendale",
    "stamp_help":            "Mostrato nell'area della firma di ogni fattura (come timbro aziendale). PNG/JPG; ridimensionato per adattarsi.",
    "upload_stamp":          "Carica timbro",
    "remove_stamp":          "Rimuovi timbro",
    "stamp_saved":           "Timbro salvato.",
    "stamp_removed":         "Timbro rimosso.",
    "invoice_customer_signature":   "Firma del cliente",
    "invoice_authorized_signature": "Firma autorizzata",
    # business contact + invoice quick-links QR buttons
    "business_contact":      "Contatto azienda & QR fattura",
    "contact_help":          "Usato per i pulsanti QR dei collegamenti rapidi della fattura (WhatsApp, scheda contatto, indicazioni).",
    "business_phone":        "Telefono azienda",
    "business_address":      "Indirizzo azienda",
    "business_maps_url":     "Link mappa / indicazioni (opzionale)",
    "business_email":        "Email azienda (opzionale)",
    "contact_saved":         "Dati di contatto salvati.",
    "pay_qr_enable":         "Abilita QR di pagamento (bonifico) sulle fatture",
    "pay_qr_help":           "Aggiunge un QR di bonifico SEPA per il saldo dovuto. Richiede l'IBAN qui sotto.",
    "business_iban":         "IBAN",
    "invoice_quick_links":   "Collegamenti rapidi — Scansiona",
    "qr_pay":                "Paga il saldo",
    "qr_whatsapp":           "Scrivici su WhatsApp",
    "qr_contact":            "Salva il contatto",
    "qr_location":           "Trovaci / riconsegna",
    "qr_summary":            "Riepilogo noleggio",
    "qr_scan_hint":          "Inquadra col telefono",
    # theme customization (super-admin) + night mode
    "select_theme":          "Scegli tema",
    "theme_font":            "Carattere",
    "theme_primary":         "Colore primario",
    "theme_secondary":       "Colore secondario",
    "theme_success":         "Colore successo",
    "theme_warning":         "Colore avviso",
    "theme_alert":           "Colore allerta",
    "theme_disabled":        "Colore disabilitato",
    "theme_bg":              "Colore sfondo",
    "theme_saved":           "Tema salvato.",
    "theme_reset":           "Ripristina predefinito",
    "theme_help":            "Scegli il carattere e i colori del marchio. Vale per tutti gli utenti.",
    "night_mode":            "Modalità notte",
    "day_mode":              "Modalità giorno",
    "tab_profile":           "Profilo",
    "profile_saved":         "Profilo aggiornato.",
    "license_records":       "Registri licenze",
    "add_license":           "Aggiungi licenza",
    "edit_license":          "Modifica licenza",
    "delete_license":        "Elimina licenza",
    "license_added":         "Licenza aggiunta.",
    "license_updated":       "Licenza aggiornata.",
    "license_deleted":       "Licenza eliminata.",
    "no_licenses":           "Nessun registro di licenza ancora.",
    "col_actions":           "Azioni",
    "to_garage":             "In garage",
    "to_maintenance":        "In manutenzione",
    "to_available":          "Rendi disponibile",
    "status_updated":        "Stato aggiornato.",
    "edit_btn":              "Modifica",
    "last_super_admin":      "Impossibile rimuovere l'ultimo super amministratore.",
    # finance totals + year lock + return activity (v3.0 round 4)
    "fin_totals":            "Totali",
    "set_licensed_year_label":"Imposta anno con licenza",
    "licensed_year_saved":   "Anno con licenza aggiornato.",
    "return_activity":       "Annulla attività",
    "activity_returned":     "Attività annullata.",
    "return_activity_help":  "Ripristina veicoli archiviati e noleggi annullati.",
    # customers split (round 5)
    "active_renters":        "Noleggiatori attivi",
    "no_active_renters":     "Nessun cliente sta noleggiando al momento.",
    "all_customers":         "Tutti i clienti",
    "open_customer":         "Apri cliente",
    # reset data + visitor hero — round 6
    "danger_zone":           "Zona pericolosa",
    "reset_finance_btn":     "Reimposta dati finanziari",
    "reset_fleet_btn":       "Reimposta dati flotta",
    "reset_finance_help":    "Elimina tutti i record di entrate (addebiti) e costi. Veicoli e noleggi vengono mantenuti.",
    "reset_fleet_help":      "Elimina tutti i veicoli, foto, noleggi e relativi dati finanziari. I clienti vengono mantenuti. La flotta predefinita viene ricaricata al prossimo riavvio.",
    "reset_confirm_label":   "Digita RESET per confermare",
    "reset_done":            "Dati reimpostati.",
    "visitor_hero":          "Sfoglia le auto disponibili",
    "visitor_hero_sub":      "Scegli l'auto giusta dalla nostra flotta. Contatta il nostro team per prenotare.",
    "contact_to_book":       "Contattaci per prenotare",
    # sidebar toggle (round 7)
    "open_sidebar":          "Apri barra laterale",
    "collapse_sidebar":      "Comprimi barra laterale",
    # data management — delete finance / client records (round 8)
    "tab_data":              "Dati",
    "data_help":             "Elimina singoli record finanziari o clienti, oppure cancellali tutti. Solo Super Amministratore.",
    "finance_records_section":"Record Finanziari",
    "client_records_section": "Record Clienti",
    "income_records":        "Entrate (Addebiti)",
    "expense_records":       "Spese (Costi)",
    "no_finance_records":    "Nessun record finanziario.",
    "col_type":              "Tipo",
    "charge_rental":         "Noleggio",
    "charge_overdue_penalty":"Penale di ritardo",
    "charge_damage":         "Danni",
    "charge_deposit":        "Cauzione",
    "charge_refund":         "Rimborso",
    "record_deleted":        "Record eliminato.",
    "client_deleted":        "Cliente e relativi noleggi eliminati.",
    "delete_client_help":    "Elimina definitivamente questo cliente con i suoi noleggi e addebiti.",
    "reset_clients_btn":     "Reimposta dati clienti",
    "reset_clients_help":    "Elimina tutti i clienti con i loro noleggi e i relativi addebiti. I veicoli vengono mantenuti e resi disponibili.",
    # edit reservation + finance reports / month drill-down (v3.1)
    "edit_reservation":      "Modifica prenotazione",
    "change_car":            "Cambia veicolo",
    "keep_current_car":      "Mantieni il veicolo attuale",
    "rental_updated":        "Prenotazione aggiornata.",
    "select_month":          "Seleziona un mese",
    "all_months":            "Tutti i mesi",
    "month_detail":          "Dettaglio mese",
    "report_total":          "TOTALE",
    "report_generated":      "Generato",
    "report_period":         "Periodo",
    "report_business":       "Azienda",
    # duplicated invoice copies (customer + office)
    "invoice_copy_customer": "Copia cliente",
    "invoice_copy_office":   "Copia ufficio",
    # add-reservation modal + timeline export range (v3.2)
    "add_reservation":       "Aggiungi prenotazione",
    "tl_export_range":       "Intervallo di esportazione",
    "tl_range_week":         "Questa settimana",
    "tl_range_month":        "Questo mese",
    "tl_range_year":         "Quest'anno",
    "tl_range_two":          "Intervallo di due mesi",
    "tl_range_all":          "Tutti i mesi (pagine separate)",
    "tl_pick_start_month":   "Mese iniziale",
    # timeline view buttons + show-done toggle (v3.3)
    "view_day":              "Giorno",
    "view_week":             "Settimana",
    "view_month":            "Mese",
    "view_year":             "Anno",
    "view_today":            "Oggi",
    "show_done":             "Mostra completati",
}

TERMS = {
    "title": "CONDIZIONI DI NOLEGGIO DEL VEICOLO E RESPONSABILITÀ PER DANNI",
    "rules": [
        "Il veicolo deve essere utilizzato nel rispetto del codice della strada. Il rispetto dei limiti di velocità è obbligatorio.",
        "Per policy aziendale la velocità massima di utilizzo dei veicoli è di 120 km/h. In caso di superamento del limite di 120 km/h, il cliente è responsabile di eventuali guasti al motore, al turbo, al cambio o di natura meccanica causati dall'eccesso di velocità. I dati GPS e le registrazioni di velocità del veicolo sono accettati come prova valida.",
        "È severamente vietato fumare all'interno del veicolo. I costi di pulizia, riparazione o sostituzione per odore di sigaretta, bruciature o danni ai sedili/rivestimenti sono a carico del cliente.",
        "I danni a sedili, rivestimenti, parti in plastica, schermo multimediale o equipaggiamento interno sono a carico del cliente.",
        "I danni derivanti da scoppi degli pneumatici, cerchi piegati, urti contro il cordolo, uso improprio o negligenza sono responsabilità del cliente.",
        "Crepe e scheggiature su parabrezza, fari, specchietti o finestrini sono a carico del cliente in caso di errore dell'utente o negligenza.",
        "Tutti i costi derivanti dall'uso di carburante errato sono a carico del cliente.",
        "In caso di smarrimento, rottura o danneggiamento della chiave del veicolo, il costo di una nuova chiave, del software e del traino è a carico del cliente.",
        "Le multe stradali, i pedaggi autostradali, le multe per la sosta e le tariffe di transito sono a carico del noleggiatore.",
        "Al momento della consegna vengono effettuate registrazioni video e fotografiche. Le condizioni del veicolo al momento della consegna sono accettate come documentazione ufficiale.",
        "L'azienda utilizza un sistema di localizzazione veicoli (GPS) per finalità di sicurezza e gestione della flotta.",
        "Il veicolo deve essere restituito con lo stesso livello di carburante con cui è stato ricevuto.",
        "Riconsegna in ritardo: il veicolo deve essere restituito entro la data e l'ora concordate. Ogni giorno iniziato di ritardo viene addebitato come un giorno di noleggio aggiuntivo completo; può inoltre essere applicata una penale per il ritardo.",
    ],
}
